import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    home: 'Home',
    webDesign: 'Web Design',
    digitalMarketing: 'Digital Marketing',
    accounting: 'Accounting Systems',
    networkServers: 'Network & Servers',
    smartControl: 'Smart Control',
    it: 'IT Services',
    mailPro: 'Mail Professional',
    cart: 'Cart',
    
    // Actions & Buttons
    getStarted: 'Get Started',
    contactUs: 'Contact Us',
    addToCart: 'Add to Cart',
    subscribeNow: 'Subscribe Now',
    learnMore: 'Learn More',
    viewDetails: 'View Details',
    allRightsReserved: 'All rights reserved.',
    requestDemo: 'Request Free Demo',
    requestQuote: 'Request Quote',
    popularChoice: 'POPULAR CHOICE',
    sale: 'SALE',

    // Pricing Labels
    currency: 'EGP',
    perMonth: '/Month',

    // Pricing Plans Translation
    planIndividual: 'Individual',
    planIndividualSub: 'Single Use',
    planBusiness: 'Business',
    planBusinessSub: 'Multiple Users',
    planProfessional: 'Professional',
    planProfessionalSub: 'Multiple Users',

    planStarterAccounting: 'Starter Accounting',
    planStarterAccountingSub: 'Small Businesses & Startups',
    planBusinessERP: 'Business ERP',
    planBusinessERPSub: 'Growing Companies',
    planEnterpriseSuite: 'Enterprise Suite',
    planEnterpriseSuiteSub: 'Large Scale Organizations',

    planStarterMarketing: 'Starter Marketing',
    planStarterMarketingSub: 'Small Businesses & Launching Brands',
    planGrowthProMarketing: 'Growth Pro Marketing',
    planGrowthProMarketingSub: 'Scaling Companies & E-Commerce',
    planEnterpriseDominance: 'Enterprise Dominance',
    planEnterpriseDominanceSub: 'Market Leaders & Multi-Brands',

    // Pricing Features Bullet Points
    feat1Mailbox: '1 mailbox included',
    feat5GB: '5GB for emails',
    featCloudInfra: 'Cloud infrastructure',
    featAntivirus: 'Antivirus check',
    feat3Mailboxes: '3 mailboxes included',
    feat30GB: '30GB for emails',
    featFullMobileSync: 'Full mobile sync support',
    feat5Mailboxes: '5 mailboxes included',
    feat75GB: '75GB for emails',
    featFreeDomain: 'Free domain',

    // Accounting Page Localization
    accountingBadge: 'ERP & FINANCIAL SYSTEMS',
    accountingHeroTitle: 'Smart Accounting & Odoo ERP Systems for Modern Enterprises',
    accountingHeroSub: 'Take full control of your company financial health, electronic invoicing, inventory, and payroll with our certified Odoo ERP and custom accounting implementations.',
    accountingCapabilities: 'CORE SYSTEM CAPABILITIES',
    everythingAccounting: 'Everything Your Enterprise Needs for Complete Financial Control',
    everythingAccountingSub: 'Streamline operations, automate tax reports, and eliminate manual errors with unified ERP software.',
    accountingPlans: 'Accounting & ERP Pricing Plans',
    accountingPlansSub: 'Flexible subscription tiers for startups, medium businesses, and large enterprise chains.',
    integrationWorkflow: 'Seamless 3-Step System Integration',
    integrationWorkflowSub: 'Our proven deployment roadmap ensuring 0% data loss and smooth staff adoption.',
    requestErpConsultation: 'Request Free ERP Consultation',
    exploreErpPlans: 'Explore ERP Plans',
    certifiedOdooPartner: 'Official Certified Odoo Implementation Partner',

    // Digital Marketing Localization
    marketingBadge: 'DIGITAL MARKETING & GROWTH',
    marketingHeroTitle: 'Data-Driven Digital Marketing & Growth Engineering',
    marketingHeroSub: 'We engineer high-ROI digital marketing campaigns, social media strategies, targeted paid advertising, and search engine dominance to scale your revenue.',
    coreMarketingPillars: 'CORE MARKETING PILLARS',
    endToEndGrowth: 'End-to-End Growth Engine for Your Brand',
    endToEndSub: 'Everything your brand needs to attract high-intent leads and maximize customer lifetime value.',
    marketingPackages: 'Growth Marketing Packages',
    marketingPackagesSub: 'Flexible monthly growth packages designed to deliver scalable ROI and brand visibility.',
    campaignShowcase: 'Omnichannel Campaign Excellence',
    campaignShowcaseSub: 'Explore our multi-channel marketing campaigns built across Facebook, Instagram, Google, and TikTok.',
    marketingWorkflow: 'Our Growth Strategy Workflow',
    marketingWorkflowSub: 'A structured data-first process to design, test, optimize, and scale your digital marketing.',
    startGrowthCampaign: 'Start Growth Campaign',
    explorePackages: 'Explore Packages',
    strategyWorkflowBadge: 'STRATEGY WORKFLOW',
    readyScaleBrand: 'Ready to Scale Your Brand Revenue?',
    readyScaleSub: 'Partner with our digital marketing specialists to launch high-converting multi-channel campaigns.',
    allChannels: 'All Channels',
    socialMediaAds: 'Social Media Ads',
    seoSearchDominance: 'SEO & Search',
    performanceMarketing: 'Performance Ads',

    // Web Design Page Localization
    webDesignBadge: 'WEB DESIGN & ENGINEERING',
    webDesignHeroTitle: 'Custom Web Design & Digital Engineering',
    webDesignHeroSub: 'We build high-performance, responsive websites and custom web applications designed to elevate your brand credibility, delight users, and drive maximum business conversions.',
    coreCapabilities: 'CORE CAPABILITIES',
    everythingNeeded: 'Everything Your Website Needs to Succeed',
    webDesignPillarsSub: 'From initial UI/UX wireframes to full-stack engineering, performance tuning, and technical SEO.',
    exploreShowcase: 'Explore Our Modern Website Showcase',
    showcaseSub: 'Discover some of our flagship website designs and interactive portal templates built for industry leaders.',
    processTitle: 'Our Web Design Process',
    processSub: 'A proven 4-stage engineering methodology to turn your concept into a live website.',
    startWebProject: 'Start Your Web Project',
    viewShowcase: 'View Project Showcase',
    portfolioShowcaseBadge: 'PORTFOLIO SHOWCASE',
    methodologyBadge: 'METHODOLOGY',
    readyLaunchWebsite: 'Ready to Launch Your Next-Gen Website?',
    readyLaunchSub: 'Let our engineering and marketing experts build your company\'s next website.',
    allProjects: 'All Projects',
    eCommerce: 'E-Commerce',
    corporate: 'Corporate',
    saasApps: 'SaaS & Apps',
    requestSimilarDesign: 'Request Similar Design',

    // Home Page Full Localization
    digitalPlatform: 'DIGITAL PLATFORM',
    heroHeading: 'Turning Ideas Into',
    heroDesc: 'We provide complete solutions in software, hardware, professional email, accounting systems, smart control, website development, and social media management — your business growth starts here.',
    webDesignAndServices: 'Web Design & Services',
    uptimeGuarantee: 'Uptime Guarantee',
    techSupport: 'Technical Support',
    globalClients: 'Global Clients',
    featuresBadge: 'FEATURES',
    allInOneTitle: 'Your All-in-One Tech Partner',
    allInOneDesc: 'From professional email and smart control to websites, accounting, and social media — our integrated services cover every step of your business growth.',
    integratedDigitalEngineering: 'Integrated Digital Engineering & Infrastructure',
    integratedDesc: 'We bring together software engineering, hardware installations, smart control systems, and enterprise accounting into a single unified partner for your organization.',
    lowCurrentCert: 'Certified Low-Current & Network Installations',
    cloudEmailCert: 'Automated Cloud Email & Domain Management',
    webErpCert: 'High-Performance Web & ERP Solutions',
    smartScalableTech: 'Smart & Scalable Tech',
    smartScalableTechDesc: 'Smart & scalable tech solutions',
    secureEmail: 'Secure Email',
    secureEmailDesc: 'Secure professional email',
    modernWebsites: 'Modern Websites',
    modernWebsitesDesc: 'Modern websites that convert',
    accountingSystems: 'Accounting Systems',
    accountingSystemsDesc: 'Accounting & business tracking',
    socialMedia: 'Social Media',
    socialMediaDesc: 'Social media that drives sales',
    proEmailCardDesc: 'Secure, branded email services that enhance your business credibility.',
    socialCardDesc: 'Engaging content and smart strategies to grow your audience and sales.',
    accCardDesc: 'Easy-to-use solutions to track finances, manage invoices, and control expenses.',
    networkCardDesc: 'Reliable, high-speed networking and server solutions built for your business.',
    pricingPlans: 'Pricing Plans',
    pricingSub: 'Choose the right professional email package for your business.',
    whatWeDo: 'WHAT WE DO',
    techSolutionsTitle: 'Tech Solutions Tailored to Your Business',
    techSolutionsSub: 'We specialize in delivering high-impact services in professional email, social media, accounting, networking, and servers — built to keep your business running smarter and faster.',
    worldwideTrust: 'WORLDWIDE TRUST',
    worldwideTrustTitle: 'Empowering Businesses with Professional Email Solutions',
    worldwideTrustSub: 'Trusted by companies worldwide for secure, branded, and reliable communication.',

    // Footer
    footerDesc: 'Empowering businesses with modern web engineering, ERP systems, smart control, and digital growth.',
    quickLinks: 'Quick Links',
    techSolutions: 'Tech Solutions',
    contactInfo: 'Contact Information'
  },
  ar: {
    // Navigation
    home: 'الرئيسية',
    webDesign: 'تصميم المواقع',
    digitalMarketing: 'التسويق الرقمي',
    accounting: 'الأنظمة المحاسبية',
    networkServers: 'الشبكات والسيرفرات',
    smartControl: 'التحكم الذكي',
    it: 'خدمات تكنولوجيا المعلومات',
    mailPro: 'بريد الشركات الاحترافي',
    cart: 'السلة',

    // Actions & Buttons
    getStarted: 'ابدأ الآن',
    contactUs: 'تواصل معنا',
    addToCart: 'أضف إلى السلة',
    subscribeNow: 'اشترك الآن',
    learnMore: 'اعرف المزيد',
    viewDetails: 'عرض التفاصيل',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    requestDemo: 'طلب تجربة مجانية',
    requestQuote: 'طلب عرض سعر',
    popularChoice: 'الأكثر طلباً',
    sale: 'خصم خاص',

    // Pricing Labels
    currency: 'ج.م',
    perMonth: '/شهرياً',

    // Pricing Plans Translation
    planIndividual: 'باقة الفردي',
    planIndividualSub: 'استخدام فردي',
    planBusiness: 'باقة الأعمال',
    planBusinessSub: 'مستخدمين متعددين',
    planProfessional: 'الباقة الاحترافية',
    planProfessionalSub: 'مستخدمين متعددين',

    planStarterAccounting: 'المحاسبة المبتدئة',
    planStarterAccountingSub: 'للشركات الناشئة والمحلات',
    planBusinessERP: 'إدارة المؤسسات ERP',
    planBusinessERPSub: 'للشركات المتنامية والمتوسطة',
    planEnterpriseSuite: 'جناح الشركات الكبرى',
    planEnterpriseSuiteSub: 'للمؤسسات الكبرى متعددة الفروع',

    planStarterMarketing: 'التسويق المبتدئ',
    planStarterMarketingSub: 'للشركات الناشئة والعلامات الجديدة',
    planGrowthProMarketing: 'باقة نمو التسويق الاحترافي',
    planGrowthProMarketingSub: 'للمتاجر والشركات للتوسع السريع',
    planEnterpriseDominance: 'الهيمنة والتوسع الشامل',
    planEnterpriseDominanceSub: 'لكبرى العلامات والقنوات المتعددة',

    // Pricing Features Bullet Points
    feat1Mailbox: 'يتضمن صندوق بريد واحد',
    feat5GB: 'مساحة 5 جيجابايت للبريد',
    featCloudInfra: 'بنية تحتية سحابية فائقة الأمان',
    featAntivirus: 'فحص دوري وحماية من الفيروسات',
    feat3Mailboxes: 'يتضمن 3 صناديق بريد رسمية',
    feat30GB: 'مساحة 30 جيجابايت للبريد',
    featFullMobileSync: 'دعم المزامنة الكاملة مع الهواتف الذكية',
    feat5Mailboxes: 'يتضمن 5 صناديق بريد رسمية',
    feat75GB: 'مساحة 75 جيجابايت للبريد',
    featFreeDomain: 'نطاق (دومين) خاص مجاني',

    // Accounting Page Localization
    accountingBadge: 'أنظمة ERP والحسابات',
    accountingHeroTitle: 'الأنظمة المحاسبية الذكية وحلول Odoo ERP للمؤسسات الحديثة',
    accountingHeroSub: 'سيطر بالكامل على الصحة المالية لشركتك والفاتورة الإلكترونية والمخازن والمرتبات مع حلول Odoo ERP المعتمدة.',
    accountingCapabilities: 'قدرات وإمكانيات النظام المحاسبي',
    everythingAccounting: 'كل ما تحتاجه مؤسستك لإدارة مالية متكاملة',
    everythingAccountingSub: 'تسهيل العمليات التشغيلية، إصدار الإقرارات الضريبية تلقائياً، وإلغاء الأخطاء اليدوية بنظام ERP موحد.',
    accountingPlans: 'خطط وأسعار الأنظمة المحاسبية والـ ERP',
    accountingPlansSub: 'باقات اشتراك مرنة تناسب الشركات الناشئة، المتوسطة، والسلاسل التجارية الكبرى.',
    integrationWorkflow: 'خطوات الربط والدمج الثلاثية',
    integrationWorkflowSub: 'خطة عمل مجربة وموثوقة لضمان نقل البيانات بدون أي فقدان 0% وتدريب فريق عملك.',
    requestErpConsultation: 'طلب استشارة ERP مجانية',
    exploreErpPlans: 'استعراض باقات ERP',
    certifiedOdooPartner: 'شريك معتمد رسمي لتطبيق وتنفيذ أنظمة Odoo',

    // Digital Marketing Localization
    marketingBadge: 'التسويق الرقمي والنمو',
    marketingHeroTitle: 'التسويق الرقمي القائم على البيانات واستراتيجيات النمو',
    marketingHeroSub: 'نقوم بصياغة حملات تسويق رقمي عالية العائد واستراتيجيات تواصل اجتماعي وإعلانات ممولة مستهدفة وتصدر محركات البحث لزيادة مبيعاتك.',
    coreMarketingPillars: 'ركائز ودعائم التسويق',
    endToEndGrowth: 'منظومة نمو متكاملة لعلامتك التجارية',
    endToEndSub: 'كل ما تحتاجه علامتك التجاريّة وجذب العملاء المهتمين وزيادة المبيعات.',
    marketingPackages: 'باقات التسويق الرقمي والنمو',
    marketingPackagesSub: 'باقات شهرية مرنة مصممة لتحقيق أعلى عائد على الاستثمار وزيادة انتشار العلامة التجارية.',
    campaignShowcase: 'معرض إعلانات وحملات التسويق',
    campaignShowcaseSub: 'استكشف حملاتنا التسويقية الناجحة عبر فيسبوك، إنستغرام، جوجل، وتيك توك.',
    marketingWorkflow: 'مسار استراتيجية النمو والتسويق',
    marketingWorkflowSub: 'منهجية منظمة قائمة على تحليلات البيانات للتصميم والاختبار والمكاسب التسويقية المستمرة.',
    startGrowthCampaign: 'ابدأ حملتك التسويقية الآن',
    explorePackages: 'استعراض الباقات',
    strategyWorkflowBadge: 'خطوات استراتيجية النمو',
    readyScaleBrand: 'هل أنت جاهز لتكبير وزيادة مبيعات علامتك التجارية؟',
    readyScaleSub: 'تواصل مع خبراء التسويق الرقمي لدينا لإطلاق حملات تسويقية متكاملة عالية العائد.',
    allChannels: 'جميع القنوات',
    socialMediaAds: 'إعلانات السوشيال ميديا',
    seoSearchDominance: 'تصدر محركات البحث',
    performanceMarketing: 'التسويق القائم على الأداء',

    // Web Design Page Localization
    webDesignBadge: 'تصميم وهندسة المواقع',
    webDesignHeroTitle: 'تصميم المواقع وتطوير الهندسة الرقمية',
    webDesignHeroSub: 'نقوم ببناء مواقع إلكترونية متجاوبة وعالية الأداء وتطبيقات ويب مخصصة لتعزيز مصداقية علامتك التجارية وزيادة المبيعات والتحويلات.',
    coreCapabilities: 'القدرات والخدمات المتاحة',
    everythingNeeded: 'كل ما يحتاجه موقعك الإلكتروني للنجاح',
    webDesignPillarsSub: 'من تصميم الواجهات سريعة التجاوب إلى البرمجة الكاملة وتصدر محركات البحث.',
    exploreShowcase: 'استكشف معرض نماذج المواقع الحديثة',
    showcaseSub: 'نماذج وتصميمات مواقع حديثة وتفاعلية مصممة خصيصاً لكبرى الشركات والمتاجر.',
    processTitle: 'مراحل وخطوات تصميم المواقع',
    processSub: 'منهجية هندسية من 4 مراحل لتحويل فكرة موقعك إلى واقع حي واحترافي.',
    startWebProject: 'ابدأ مشروع موقعك الآن',
    viewShowcase: 'استعراض النماذج',
    portfolioShowcaseBadge: 'معرض الأعمال',
    methodologyBadge: 'خطوات العمل',
    readyLaunchWebsite: 'هل أنت جاهز لإطلاق موقعك الإلكتروني الحديث؟',
    readyLaunchSub: 'دع خبراء البرمجة والتسويق لدينا يبنون الموقع القادم لشركتك بأحدث المعايير.',
    allProjects: 'جميع المشاريع',
    eCommerce: 'المتاجر الإلكترونية',
    corporate: 'مواقع الشركات',
    saasApps: 'المنصات والتطبيقات',
    requestSimilarDesign: 'طلب تصميم مماثل',

    // Home Page Full Localization
    digitalPlatform: 'منصة رقمية',
    heroHeading: 'تحويل الأفكار إلى',
    heroDesc: 'نحن نقدم حلولاً متكاملة في البرمجيات والأجهزة والبريد الإلكتروني الاحترافي والأنظمة المحاسبية والتحكم الذكي وتطوير المواقع والتسويق — نمو أعمالك يبدأ من هنا.',
    webDesignAndServices: 'تصميم المواقع والخدمات',
    uptimeGuarantee: 'ضمان تشغيل واستقرار 99.9%',
    techSupport: 'دعم فني متواصل 24/7',
    globalClients: 'عميل محلي وعالمي',
    featuresBadge: 'المميزات',
    allInOneTitle: 'شريكك التقني المتكامل',
    allInOneDesc: 'من البريد الاحترافي والتحكم الذكي إلى المواقع الإلكترونية والمحاسبة والتسويق — خدماتنا تغطي جميع مراحل نمو عملك.',
    integratedDigitalEngineering: 'الهندسة الرقمية والبنية التحتية المتكاملة',
    integratedDesc: 'نجمع بين هندسة البرمجيات، تركيبات الشبكات والأنظمة، شبكات التحكم الذكي، وأنظمة ERP المحاسبية تحت سقف شريك تقني واحد لمؤسستك.',
    lowCurrentCert: 'تركيبات وشبكات معتمدة وشاملة',
    cloudEmailCert: 'إدارة السيرفرات والنطاقات والبريد السحابي',
    webErpCert: 'حلول الويب المتقدمة وأنظمة الـ ERP',
    smartScalableTech: 'تكنولوجيا ذكية وقابلة للتوسع',
    smartScalableTechDesc: 'حلول تقنية ذكية وقابلة للنمو',
    secureEmail: 'بريد سحابي آمن',
    secureEmailDesc: 'بريد إلكتروني مخصص ومؤمن بالكامل',
    modernWebsites: 'مواقع حديثة عالية الأداء',
    modernWebsitesDesc: 'مواقع إلكترونية سريعة وجذابة',
    accountingSystems: 'أنظمة محاسبية متطورة',
    accountingSystemsDesc: 'متابعة وإدارة الحسابات بدقة',
    socialMedia: 'تسويق رقمي وإعلانات',
    socialMediaDesc: 'تسويق رقمي يزيد مبيعاتك',
    proEmailCardDesc: 'خدمات بريد إلكتروني رسمية ومؤمنة تعزز مصداقية واسم عملك التجاري.',
    socialCardDesc: 'محتوى جذاب وإستراتيجيات تسويقية لزيادة متابعيك ومبيعاتك.',
    accCardDesc: 'حلول سهلة لإدارة الحسابات، إصدار الفواتير الإلكترونية، والتحكم بالمرتبات.',
    networkCardDesc: 'شبكات وسيرفرات فائقة السرعة معتمدة لحماية واستقرار شركتك.',
    pricingPlans: 'خطط الأسعار',
    pricingSub: 'اختر باقة البريد الإلكتروني أو الحل المناسب لشركتك.',
    whatWeDo: 'ماذا نقدم',
    techSolutionsTitle: 'حلول تقنية مخصصة لنشاطك التجاري',
    techSolutionsSub: 'نحن متخصصون في تقديم خدمات عالية التأثير في البريد الإلكتروني، شبكات التواصل، المحاسبة، الشبكات والسيرفرات.',
    worldwideTrust: 'ثقة عالمية ومحلية',
    worldwideTrustTitle: 'تمكين الشركات بحلول البريد الإلكتروني والأنظمة التقنية',
    worldwideTrustSub: 'محل ثقة كبرى الشركات والتجار لتوفير اتصالات وأنظمة آمنة وموثوقة.',

    // Footer
    footerDesc: 'تمكين الشركات والمؤسسات بأحدث تكنولوجيات البرمجة، أنظمة ERP المحاسبية، التحكم الذكي، والتسويق الرقمي.',
    quickLinks: 'روابط سريعة',
    techSolutions: 'الحلول التقنية',
    contactInfo: 'معلومات الاتصال'
  },
  fr: {
    // Navigation
    home: 'Accueil',
    webDesign: 'Conception Web',
    digitalMarketing: 'Marketing Digital',
    accounting: 'Systèmes Comptables',
    networkServers: 'Réseaux & Serveurs',
    smartControl: 'Contrôle Intelligent',
    it: 'Services Informatiques',
    mailPro: 'E-mail Professionnel',
    cart: 'Panier',

    // Actions & Buttons
    getStarted: 'Commencer',
    contactUs: 'Contactez-nous',
    addToCart: 'Ajouter au panier',
    subscribeNow: "S'abonner",
    learnMore: 'En savoir plus',
    viewDetails: 'Voir les détails',
    allRightsReserved: 'Tous droits réservés.',
    requestDemo: 'Demander une démo',
    requestQuote: 'Demander un devis',
    popularChoice: 'CHOIX POPULAIRE',
    sale: 'PROMOTION',

    // Pricing Labels
    currency: 'EGP',
    perMonth: '/Mois',

    // Pricing Plans Translation
    planIndividual: 'Individuel',
    planIndividualSub: 'Usage Unique',
    planBusiness: 'Business',
    planBusinessSub: 'Utilisateurs Multiples',
    planProfessional: 'Professionnel',
    planProfessionalSub: 'Utilisateurs Multiples',

    planStarterAccounting: 'Comptabilité Débutant',
    planStarterAccountingSub: 'Petites Entreprises',
    planBusinessERP: 'ERP Entreprise',
    planBusinessERPSub: 'Entreprises en Croissance',
    planEnterpriseSuite: 'Suite Entreprise',
    planEnterpriseSuiteSub: 'Grandes Organisations',

    planStarterMarketing: 'Marketing Débutant',
    planStarterMarketingSub: 'Marques en Lancement',
    planGrowthProMarketing: 'Marketing Croissance Pro',
    planGrowthProMarketingSub: 'E-Commerce & Scalabilité',
    planEnterpriseDominance: 'Dominance Entreprise',
    planEnterpriseDominanceSub: 'Lois du Marché',

    // Pricing Features Bullet Points
    feat1Mailbox: '1 boîte aux lettres incluse',
    feat5GB: '5 Go pour les e-mails',
    featCloudInfra: 'Infrastructure Cloud sécurisée',
    featAntivirus: 'Protection antivirus',
    feat3Mailboxes: '3 boîtes aux lettres incluses',
    feat30GB: '30 Go pour les e-mails',
    featFullMobileSync: 'Synchronisation mobile complète',
    feat5Mailboxes: '5 boîtes aux lettres incluses',
    feat75GB: '75 Go pour les e-mails',
    featFreeDomain: 'Nom de domaine gratuit',

    // Accounting Page Localization
    accountingBadge: 'SYSTÈMES ERP & COMPTABILITÉ',
    accountingHeroTitle: 'Comptabilité Intelligente & Systèmes Odoo ERP',
    accountingHeroSub: 'Prenez le contrôle total de la santé financière de votre entreprise, de la facturation électronique et de la paie avec Odoo ERP.',
    accountingCapabilities: 'CAPACITÉS DU SYSTÈME',
    everythingAccounting: 'Tout ce dont votre entreprise a besoin',
    everythingAccountingSub: 'Simplifiez vos opérations et automatisez vos rapports fiscaux.',
    accountingPlans: 'Plans Tarifs Comptabilité & ERP',
    accountingPlansSub: 'Abonnements flexibles pour toutes les tailles d\'entreprises.',
    integrationWorkflow: 'Intégration en 3 Étapes',
    integrationWorkflowSub: 'Processus de déploiement garanti 0% perte de données.',
    requestErpConsultation: 'Demander une Consultation ERP',
    exploreErpPlans: 'Explorer les Plans ERP',
    certifiedOdooPartner: 'Partenaire Officiel Certifié Odoo ERP',

    // Digital Marketing Localization
    marketingBadge: 'MARKETING DIGITAL & CROISSANCE',
    marketingHeroTitle: 'Marketing Digital Basé sur les Données & Croissance',
    marketingHeroSub: 'Nous concevons des campagnes marketing à fort ROI, des stratégies médias sociaux et des publicités ciblées pour développer vos revenus.',
    coreMarketingPillars: 'PILES DU MARKETING',
    endToEndGrowth: 'Moteur de Croissance Complet pour Votre Marque',
    endToEndSub: 'Tout ce dont votre marque a besoin pour attirer des clients qualifiés.',
    marketingPackages: 'Packages Marketing & Croissance',
    marketingPackagesSub: 'Forfaits mensuels souples conçus pour générer un ROI évolutif.',
    campaignShowcase: 'Excellence des Campagnes',
    campaignShowcaseSub: 'Explorez nos campagnes phares sur Facebook, Instagram, Google et TikTok.',
    marketingWorkflow: 'Notre Processus de Croissance',
    marketingWorkflowSub: 'Une méthodologie axée sur les données pour créer et optimiser vos campagnes.',
    startGrowthCampaign: 'Lancer une Campagne de Croissance',
    explorePackages: 'Explorer les Packages',
    strategyWorkflowBadge: 'WORKFLOW DE STRATÉGIE',
    readyScaleBrand: 'Prêt à augmenter les revenus de votre marque ?',
    readyScaleSub: 'Collaborez avec nos experts en marketing digital dès aujourd\'hui.',
    allChannels: 'Toutes les Chaînes',
    socialMediaAds: 'Ads Réseaux Sociaux',
    seoSearchDominance: 'Référencement SEO',
    performanceMarketing: 'Marketing de Performance',

    // Web Design Page Localization
    webDesignBadge: 'CONCEPTION & INGÉNIERIE WEB',
    webDesignHeroTitle: 'Conception Web Sur Mesure & Ingénierie Numérique',
    webDesignHeroSub: 'Nous construisons des sites web performants, réactifs et des applications sur mesure pour renforcer votre crédibilité et stimuler vos conversions.',
    coreCapabilities: 'CAPACITÉS PRINCIPALES',
    everythingNeeded: 'Tout ce dont votre site a besoin pour réussir',
    webDesignPillarsSub: 'Des maquettes UI/UX au développement full-stack et SEO technique.',
    exploreShowcase: 'Explorez Notre Vitrine de Sites Web',
    showcaseSub: 'Découvrez nos projets phares conçus pour les leaders du marché.',
    processTitle: 'Notre Processus de Conception Web',
    processSub: 'Une méthodologie éprouvée en 4 étapes pour concrétiser votre projet web.',
    startWebProject: 'Démarrer Votre Projet Web',
    viewShowcase: 'Voir la Vitrine',
    portfolioShowcaseBadge: 'VITRINE PORTFOLIO',
    methodologyBadge: 'MÉTHODOLOGIE',
    readyLaunchWebsite: 'Prêt à lancer votre prochain site web ?',
    readyLaunchSub: 'Laissez nos experts créer le nouveau site de votre entreprise.',
    allProjects: 'Tous les Projets',
    eCommerce: 'E-Commerce',
    corporate: 'Entreprise',
    saasApps: 'SaaS & Applications',
    requestSimilarDesign: 'Demander un Design Similaire',

    // Home Page Full Localization
    digitalPlatform: 'PLATEFORME NUMÉRIQUE',
    heroHeading: 'Transformer les idées en',
    heroDesc: 'Nous fournissons des solutions complètes en logiciels, matériel, e-mail professionnel, systèmes comptables, contrôle intelligent et développement web.',
    webDesignAndServices: 'Conception Web & Services',
    uptimeGuarantee: 'Garantie de Disponibilité 99.9%',
    techSupport: 'Support Technique 24/7',
    globalClients: 'Clients Mondiaux',
    featuresBadge: 'FONCTIONNALITÉS',
    allInOneTitle: 'Votre Partenaire Tech Tout-en-Un',
    allInOneDesc: 'De l’e-mail professionnel au contrôle intelligent en passant par les sites web et la comptabilité — nos services couvrent chaque étape de votre croissance.',
    integratedDigitalEngineering: 'Ingénierie & Infrastructure Numérique Intégrée',
    integratedDesc: 'Nous réunissons ingénierie logicielle, réseaux, systèmes intelligents et comptabilité d\'entreprise sous un même partenaire.',
    lowCurrentCert: 'Installations Réseaux Certifiées',
    cloudEmailCert: 'Gestion E-mail Cloud & Domaines',
    webErpCert: 'Solutions Web & ERP Hautes Performances',
    smartScalableTech: 'Tech Intelligente & Scalable',
    smartScalableTechDesc: 'Solutions technologiques évolutives',
    secureEmail: 'E-mail Sécurisé',
    secureEmailDesc: 'E-mail professionnel sécurisé',
    modernWebsites: 'Sites Web Modernes',
    modernWebsitesDesc: 'Sites web modernes qui convertissent',
    accountingSystems: 'Systèmes Comptables',
    accountingSystemsDesc: 'Gestion comptable & suivi',
    socialMedia: 'Médias Sociaux',
    socialMediaDesc: 'Marketing réseaux sociaux dynamique',
    proEmailCardDesc: 'Services d\'e-mail sécurisés qui renforcent votre crédibilité.',
    socialCardDesc: 'Contenu captivant et stratégies intelligentes pour développer vos ventes.',
    accCardDesc: 'Solutions simples pour suivre vos finances et gérer vos factures.',
    networkCardDesc: 'Réseaux et serveurs haute vitesse conçus pour votre entreprise.',
    pricingPlans: 'Plans de Tarification',
    pricingSub: 'Choisissez le forfait e-mail professionnel adapté à votre entreprise.',
    whatWeDo: 'CE QUE NOUS FAISONS',
    techSolutionsTitle: 'Solutions Tech Adaptées à Votre Entreprise',
    techSolutionsSub: 'Nous sommes spécialisés dans les services haute performance.',
    worldwideTrust: 'CONFIANCE MONDIALE',
    worldwideTrustTitle: 'Autonomiser les Entreprises avec des Solutions E-mail',
    worldwideTrustSub: 'Approuvé par des entreprises du monde entier.',

    // Footer
    footerDesc: "Autonomiser les entreprises grâce à l'ingénierie web moderne, aux systèmes ERP et au contrôle intelligent.",
    quickLinks: 'Liens Rapides',
    techSolutions: 'Solutions Tech',
    contactInfo: 'Informations de Contact'
  },
  hi: {
    // Navigation
    home: 'मुख्य पृष्ठ',
    webDesign: 'वेब डिजाइनिंग',
    digitalMarketing: 'डिजिटल मार्केटिंग',
    accounting: 'अकाउंटिंग सिस्टम',
    networkServers: 'नेटवर्क और सर्वर',
    smartControl: 'स्मार्ट कंट्रोल',
    it: 'आईटी सेवाएं',
    mailPro: 'प्रोफेशनल ईमेल',
    cart: 'कार्ट',

    // Actions & Buttons
    getStarted: 'शुरू करें',
    contactUs: 'संपर्क करें',
    addToCart: 'कार्ट में जोड़ें',
    subscribeNow: 'अभी सदस्यता लें',
    learnMore: 'और जानें',
    viewDetails: 'विवरण देखें',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    requestDemo: 'मुफ्त डेमो मांगें',
    requestQuote: 'कोटेशन मांगें',
    popularChoice: 'लोकप्रिय विकल्प',
    sale: 'सेल',

    // Pricing Labels
    currency: 'ईजीपी',
    perMonth: '/माह',

    // Pricing Plans Translation
    planIndividual: 'व्यक्तिगत',
    planIndividualSub: 'एकल उपयोग',
    planBusiness: 'बिजनेस',
    planBusinessSub: 'अनेक उपयोगकर्ता',
    planProfessional: 'प्रोफेशनल',
    planProfessionalSub: 'अनेक उपयोगकर्ता',

    planStarterAccounting: 'स्टार्टर अकाउंटिंग',
    planStarterAccountingSub: 'छोटे व्यवसाय',
    planBusinessERP: 'बिजनेस ईआरपी',
    planBusinessERPSub: 'बढ़ती कंपनियां',
    planEnterpriseSuite: 'एंटरप्राइज सूट',
    planEnterpriseSuiteSub: 'बडे संगठन',

    planStarterMarketing: 'स्टार्टर मार्केटिंग',
    planStarterMarketingSub: 'ब्रांड्स',
    planGrowthProMarketing: 'ग्रोथ प्रो मार्केटिंग',
    planGrowthProMarketingSub: 'ई-कॉमर्स',
    planEnterpriseDominance: 'एंटरप्राइज डोमिनेंस',
    planEnterpriseDominanceSub: 'मार्केट लीडर्स',

    // Pricing Features Bullet Points
    feat1Mailbox: '1 मेलबॉक्स शामिल',
    feat5GB: 'ईमेल के लिए 5GB',
    featCloudInfra: 'क्लाउड इंफ्रास्ट्रक्चर',
    featAntivirus: 'एंटीवायरस सुरक्षा',
    feat3Mailboxes: '3 मेलबॉक्स शामिल',
    feat30GB: 'ईमेल के लिए 30GB',
    featFullMobileSync: 'पूर्ण मोबाइल सिंक सहायता',
    feat5Mailboxes: '5 मेलबॉक्स शामिल',
    feat75GB: 'ईमेल के लिए 75GB',
    featFreeDomain: 'मुफ्त डोमेन',

    // Accounting Page Localization
    accountingBadge: 'ईआरपी और वित्तीय प्रणाली',
    accountingHeroTitle: 'आधुनिक उद्यमों के लिए स्मार्ट अकाउंटिंग और ओडू ईआरपी सिस्टम',
    accountingHeroSub: 'हमारे प्रमाणित ओडू ईआरपी कार्यान्वयन के साथ कंपनी के वित्तीय स्वास्थ्य, ई-इनवॉइसिंग और पेरोल पर पूर्ण नियंत्रण पाएं।',
    accountingCapabilities: 'सिस्टम क्षमताएं',
    everythingAccounting: 'वित्तीय नियंत्रण के लिए सब कुछ',
    everythingAccountingSub: 'ऑपरेशन्स को सुगम बनाएं।',
    accountingPlans: 'अकाउंटिंग और ईआरपी योजनाएं',
    accountingPlansSub: 'लचीली सदस्यता योजनाएं।',
    integrationWorkflow: '3-चरण एकीकरण प्रक्रिया',
    integrationWorkflowSub: '0% डेटा हानि गारंटी।',
    requestErpConsultation: 'मुफ्त ईआरपी परामर्श लें',
    exploreErpPlans: 'ईआरपी योजनाएं देखें',
    certifiedOdooPartner: 'आधिकारिक प्रमाणित ओडू कार्यान्वयन भागीदार',

    // Digital Marketing Localization
    marketingBadge: 'डिजिटल मार्केटिंग और ग्रोथ',
    marketingHeroTitle: 'डेटा-ड्रिवन डिजिटल मार्केटिंग और ग्रोथ इंजीनियरिंग',
    marketingHeroSub: 'हम उच्च आरओआई डिजिटल मार्केटिंग अभियानों, सोशल मीडिया रणनीतियों और लक्षित विज्ञापनों के माध्यम से राजस्व बढ़ाते हैं।',
    coreMarketingPillars: 'मुख्य मार्केटिंग स्तंभ',
    endToEndGrowth: 'आपके ब्रांड के लिए एंड-टू-एंड ग्रोथ इंजन',
    endToEndSub: 'आपके ब्रांड को उच्च राजस्व प्राप्त करने के लिए सब कुछ।',
    marketingPackages: 'ग्रोथ मार्केटिंग पैकेज',
    marketingPackagesSub: 'लचीली मासिक योजनाएं।',
    campaignShowcase: 'मल्टी-चैनल अभियान शोकेस',
    campaignShowcaseSub: 'फेसबुक, इंस्टाग्राम और गूगल पर हमारे सफल अभियान देखें।',
    marketingWorkflow: 'ग्रोथ रणनीति वर्कफ़्लो',
    marketingWorkflowSub: 'डेटा-प्रथम प्रक्रिया।',
    startGrowthCampaign: 'ग्रोथ कैंपेन शुरू करें',
    explorePackages: 'पैकेज देखें',
    strategyWorkflowBadge: 'रणनीति वर्कफ़्लो',
    readyScaleBrand: 'क्या आप अपने ब्रांड का राजस्व बढ़ाने के लिए तैयार हैं?',
    readyScaleSub: 'हमारे डिजिटल मार्केटिंग विशेषज्ञों से संपर्क करें।',
    allChannels: 'सभी चैनल',
    socialMediaAds: 'सोशल मीडिया विज्ञापन',
    seoSearchDominance: 'एसईओ और खोज',
    performanceMarketing: 'परफॉर्मेंस मार्केटिंग',

    // Web Design Page Localization
    webDesignBadge: 'वेब डिजाइन और इंजीनियरिंग',
    webDesignHeroTitle: 'कस्टम वेब डिजाइनिंग और डिजिटल इंजीनियरिंग',
    webDesignHeroSub: 'हम आपके ब्रांड की विश्वसनीयता बढ़ाने और अधिकतम रूपांतरण लाने के लिए उच्च प्रदर्शन वाली वेबसाइटें और ऐप बनाते हैं।',
    coreCapabilities: 'मुख्य क्षमताएं',
    everythingNeeded: 'आपकी वेबसाइट की सफलता के लिए सब कुछ',
    webDesignPillarsSub: 'यूआई/यूएक्स से लेकर फुल-स्टैक डेवलपमेंट तक।',
    exploreShowcase: 'हमारी आधुनिक वेबसाइट शोकेस देखें',
    showcaseSub: 'उद्योग जगत के प्रमुख ब्रांड्स के लिए डिज़ाइन किए गए प्रोजेक्ट्स।',
    processTitle: 'हमारी वेब डिजाइन प्रक्रिया',
    processSub: '4-चरणों की सिद्ध इंजीनियरिंग पद्धति।',
    startWebProject: 'अपना वेब प्रोजेक्ट शुरू करें',
    viewShowcase: 'शोकेस देखें',
    portfolioShowcaseBadge: 'पोर्टफोलियो शोकेस',
    methodologyBadge: 'कार्यप्रणाली',
    readyLaunchWebsite: 'क्या आप अपनी नई वेबसाइट लॉन्च करने के लिए तैयार हैं?',
    readyLaunchSub: 'हमारे विशेषज्ञों को अपनी कंपनी के लिए वेबसाइट बनाने दें।',
    allProjects: 'सभी प्रोजेक्ट',
    eCommerce: 'ई-कॉमर्स',
    corporate: 'कॉरपोरेट',
    saasApps: 'सास और ऐप्स',
    requestSimilarDesign: 'ऐसा ही डिज़ाइन मांगें',

    // Home Page Full Localization
    digitalPlatform: 'डिजिटल प्लेटफॉर्म',
    heroHeading: 'विचारों को बदलना',
    heroDesc: 'हम सॉफ्टवेयर, हार्डवेयर, प्रोफेशनल ईमेल, अकाउंटिंग सिस्टम, स्मार्ट कंट्रोल और वेब डेवलपमेंट में संपूर्ण समाधान प्रदान करते हैं।',
    webDesignAndServices: 'वेब डिजाइनिंग और सेवाएं',
    uptimeGuarantee: '99.9% अपटाइम गारंटी',
    techSupport: '24/7 तकनीकी सहायता',
    globalClients: 'वैश्विक ग्राहक',
    featuresBadge: 'विशेषताएं',
    allInOneTitle: 'आपका ऑल-इन-वन टेक पार्टनर',
    allInOneDesc: 'प्रोफेशनल ईमेल से लेकर स्मार्ट कंट्रोल, वेब पोर्टल और अकाउंटिंग तक — हमारी सेवाएं आपके व्यवसाय को बढ़ाती हैं।',
    integratedDigitalEngineering: 'एकीकृत डिजिटल इंजीनियरिंग और इंफ्रास्ट्रक्चर',
    integratedDesc: 'हम सॉफ्टवेयर, नेटवर्क, स्मार्ट कंट्रोल और ईआरपी को एक साथ लाते हैं।',
    lowCurrentCert: 'प्रमाणित नेटवर्क इंस्टॉलेशन',
    cloudEmailCert: 'क्लाउड ईमेल और डोमेन प्रबंधन',
    webErpCert: 'उच्च प्रदर्शन वेब और ईआरपी',
    smartScalableTech: 'स्मार्ट और स्केलेबल टेक',
    smartScalableTechDesc: 'स्मार्ट तकनीक समाधान',
    secureEmail: 'सुरक्षित ईमेल',
    secureEmailDesc: 'सुरक्षित व्यावसायिक ईमेल',
    modernWebsites: 'आधुनिक वेबसाइटें',
    modernWebsitesDesc: 'रूपांतरण करने वाली वेबसाइटें',
    accountingSystems: 'अकाउंटिंग सिस्टम',
    accountingSystemsDesc: 'वित्तीय ट्रैकिंग',
    socialMedia: 'सोशल मीडिया',
    socialMediaDesc: 'बिक्री बढ़ाने वाला मीडिया',
    proEmailCardDesc: 'सुरक्षित ईमेल सेवाएं जो विश्वसनीयता बढ़ाती हैं।',
    socialCardDesc: 'बिक्री बढ़ाने के लिए आकर्षक सामग्री।',
    accCardDesc: 'वित्त और चालान प्रबंधित करने के लिए समाधान।',
    networkCardDesc: 'व्यवसाय के लिए हाई-स्पीड नेटवर्क समाधान।',
    pricingPlans: 'मूल्य निर्धारण योजनाएं',
    pricingSub: 'अपने व्यवसाय के लिए सही ईमेल पैकेज चुनें।',
    whatWeDo: 'हम क्या करते हैं',
    techSolutionsTitle: 'आपके व्यवसाय के लिए अनुकूलित समाधान',
    techSolutionsSub: 'हम व्यावसायिक ईमेल और तकनीक में विशेषज्ञ हैं।',
    worldwideTrust: 'वैश्विक विश्वास',
    worldwideTrustTitle: 'व्यावसायिक ईमेल समाधानों से सशक्त बनाना',
    worldwideTrustSub: 'दुनिया भर की कंपनियों द्वारा विश्वसनीय।',

    // Footer
    footerDesc: 'आधुनिक वेब इंजीनियरिंग, ईआरपी सिस्टम, स्मार्ट कंट्रोल और डिजिटल विकास के साथ व्यवसायों को सशक्त बनाना।',
    quickLinks: 'त्वरित लिंक',
    techSolutions: 'टेक समाधान',
    contactInfo: 'संपर्क विवरण'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('pom_app_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('pom_app_lang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
