import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    home: 'Home',
    webDesign: 'Web Design',
    digitalMarketing: 'Digital Marketing',
    accounting: 'Accounting Systems',
    networkServers: 'Network & Servers',
    smartControl: 'Smart Control',
    it: 'IT Services',
    mailPro: 'Mail Professional',
    cart: 'Cart',
    
    // Actions & Buttons
    getStarted: 'Get Started',
    contactUs: 'Contact Us',
    addToCart: 'Add to Cart',
    subscribeNow: 'Subscribe Now',
    learnMore: 'Learn More',
    viewDetails: 'View Details',
    allRightsReserved: 'All rights reserved.',
    requestDemo: 'Request Free Demo',
    requestQuote: 'Request Quote',
    popularChoice: 'POPULAR CHOICE',
    sale: 'SALE',

    // Pricing Labels
    currency: 'EGP',
    perMonth: '/Month',

    // Terms & Conditions Localization
    legalBadge: 'LEGAL & PRIVACY',
    termsTitle: 'Terms and Conditions & POM Privacy Policy',
    lastUpdated: 'Last Updated: 2026',

    termsSec1Title: '1. POM Privacy Policy',
    termsSec1P1: 'This Privacy Policy (hereinafter referred to as "Policy") shall govern the manner in which POM Agency collects, uses, maintains, and discloses information obtained when you access POM\'s Website and digital services.',
    termsSec1P2: 'This Policy may be subjected to change from time to time and such change shall be effective upon being posted on POM\'s Website. Continuous access and use of POM\'s services constitutes acceptance of all terms.',

    termsSec2Title: '2. Professional Email & IT Service Terms',
    termsSec2P1: 'POM Agency provides professional email hosting, server infrastructure, website design, smart control systems, and accounting software (Odoo ERP) implementations. All service subscriptions renew according to the chosen billing cycle.',
    termsSec2Bullet1: 'Users must adhere to acceptable email usage policies and anti-spam standards.',
    termsSec2Bullet2: 'Mailbox storage allocations are determined by the subscribed tier (Individual: 5GB, Business: 30GB, Professional: 75GB).',
    termsSec2Bullet3: '24/7 technical support and network monitoring are available for active hosting and server clients.',

    termsSec3Title: '3. Intellectual Property & Trademarks',
    termsSec3P1: 'Copyright © 2021 – 2026 pomagency Operating Company, All Rights Reserved. The pomagency word mark and logo are registered trademarks.',

    // Pricing Plans Translation
    planIndividual: 'Individual',
    planIndividualSub: 'Single Use',
    planBusiness: 'Business',
    planBusinessSub: 'Multiple Users',
    planProfessional: 'Professional',
    planProfessionalSub: 'Multiple Users',

    planStarterAccounting: 'Starter Accounting',
    planStarterAccountingSub: 'Small Businesses & Startups',
    planBusinessERP: 'Business ERP',
    planBusinessERPSub: 'Growing Companies',
    planEnterpriseSuite: 'Enterprise Suite',
    planEnterpriseSuiteSub: 'Large Scale Organizations',

    planStarterMarketing: 'Starter Marketing',
    planStarterMarketingSub: 'Small Businesses & Launching Brands',
    planGrowthProMarketing: 'Growth Pro Marketing',
    planGrowthProMarketingSub: 'Scaling Companies & E-Commerce',
    planEnterpriseDominance: 'Enterprise Dominance',
    planEnterpriseDominanceSub: 'Market Leaders & Multi-Brands',

    planStarterIT: 'Starter IT Support',
    planStarterITSub: 'Small Businesses & Remote Teams',
    planManagedITPro: 'Managed IT Pro',
    planManagedITProSub: 'Medium Companies & Offices',
    planEnterpriseCareSLA: 'Enterprise Care SLA',
    planEnterpriseCareSLASub: 'Large Corporations & Multi-Sites',

    // Pricing Features Bullet Points
    feat1Mailbox: '1 mailbox included',
    feat5GB: '5GB for emails',
    featCloudInfra: 'Cloud infrastructure',
    featAntivirus: 'Antivirus check',
    feat3Mailboxes: '3 mailboxes included',
    feat30GB: '30GB for emails',
    featFullMobileSync: 'Full mobile sync support',
    feat5Mailboxes: '5 mailboxes included',
    feat75GB: '75GB for emails',
    featFreeDomain: 'Free domain',

    // IT Services Page Localization
    itBadge: 'MANAGED IT SERVICES',
    itHeroTitle: 'Enterprise Managed IT Services & Infrastructure Support',
    itHeroSub: 'We provide 24/7 managed IT support, cybersecurity protection, cloud infrastructure management, hardware maintenance, and SLA-guaranteed helpdesk support.',
    coreITServices: 'CORE MANAGED IT SERVICES',
    everythingIT: 'Complete Managed IT & Cybersecurity Support Built for Your Enterprise',
    everythingITSub: 'Minimize downtime, secure your business data, and accelerate digital transformation with certified IT engineers.',
    itPackages: 'Managed IT Support Packages',
    itPackagesSub: 'Flexible SLA tiers offering remote helpdesk, on-site hardware maintenance, and proactive network monitoring.',
    requestITAudit: 'Request Free IT Audit',
    exploreITPackages: 'Explore IT Packages',
    itServicesCtaTitle: 'Ready to Elevate Your Company IT Reliability & Security?',
    itServicesCtaSub: 'Schedule an on-site IT audit and infrastructure roadmap with our certified team.',
    managedItTag: 'Managed IT Service',

    // Mail Professional Page Localization
    mailBadge: 'FEATURES',
    mailHeroTitle: 'Create a professional email for your business',
    mailHeroSub: 'An email address that matches your custom domain to make your brand appear more credible. Boost team collaboration, enhance data security, and establish customer trust with custom domain email hosting.',
    customDomainAccounts: 'Custom domain name email accounts',
    cloudInfraSecurity: 'Enterprise cloud infrastructure & antivirus protection',
    mobileDesktopSync: 'Full smartphone & desktop sync support',
    howItWorks: '4 Steps to Setup Your Professional Email',
    howItWorksSub: 'Get your custom domain email live in minutes.',

    step1Title: 'Create a professional email for your business',
    step1Desc: 'An email address that matches your custom domain to make your brand appear more credible.',
    step2Title: 'Choose an email hosting plan',
    step2Desc: 'Are you running a new business? Follow the Individual, Business, or Professional hosting plans.',
    step3Title: 'Go to payment',
    step3Desc: 'Select the number of mailboxes and the subscription period. After the payment process is complete, you will be directed to your hosting account control panel.',
    step4Title: 'Configure your email hosting',
    step4Desc: 'Finally, create an email account, set up DNS settings, and sync your email with other devices. All that\'s left is to send your emails.',

    needMore: 'Need more? Get a custom plan',
    needMoreDesc: 'If you need more than 50 email accounts or want Private Email for more than 20 domains, reach out, and one of our team will create a custom plan for your business.',

    servicesBadge: 'SERVICES',
    aiDevTitle: 'AI Development: Cutting-Edge Solutions for Your Industry',
    aiDevSub: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.',
    seoOptimization: 'SEO Optimization',
    seoOptDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.',
    socialEngagement: 'Social Engagement',
    socialEngDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.',
    contentMarketing: 'Content Marketing',
    contentMktDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.',

    companyTimelineBadge: 'COMPANY TIMELINE',
    companyTimelineTitle: 'Company Timeline',
    companyTimelineSub: 'Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo luctus nec ullamcorper.',

    event1Title: 'Founded in USA',
    event1Desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima incidunt voluptates nemo.',
    event2Title: 'Opening New Office',
    event2Desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima incidunt voluptates nemo.',
    event3Title: 'Client Satisfaction',
    event3Desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima incidunt voluptates nemo.',
    event4Title: 'Improved Ourselves',
    event4Desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima incidunt voluptates nemo.',

    getInTouch: 'Get in touch',

    // Network & Servers Page Localization
    networkBadge: 'ENTERPRISE INFRASTRUCTURE',
    networkHeroTitle: 'High-Performance Network & Server Engineering',
    networkHeroSub: 'We design, install, and secure high-speed enterprise networks, dedicated servers, Active Directory domains, and automated backup infrastructure.',
    coreNetworkServices: 'CORE INFRASTRUCTURE SERVICES',
    everythingNetwork: 'Certified Network & Server Solutions Built for Maximum Uptime',
    everythingNetworkSub: 'Engineered for 99.99% network reliability, zero data loss, and ironclad firewall security.',
    serverArchitectures: 'Custom Enterprise Server Architectures',
    serverArchitecturesSub: 'High-capacity server hardware engineered for virtualization, storage, and domain control.',
    requestNetworkConsultation: 'Request Network Consultation',
    exploreServerSolutions: 'Explore Server Solutions',
    customBlueprintBadge: 'CUSTOM BLUEPRINT',
    needCustomBlueprint: 'Need a Custom Enterprise Network Blueprint?',
    needCustomBlueprintSub: 'Contact our certified network engineers for an on-site network audit and architecture proposal.',

    // Accounting Page Localization
    accountingBadge: 'ERP & FINANCIAL SYSTEMS',
    accountingHeroTitle: 'Smart Accounting & Odoo ERP Systems for Modern Enterprises',
    accountingHeroSub: 'Take full control of your company financial health, electronic invoicing, inventory, and payroll with our certified Odoo ERP and custom accounting implementations.',
    accountingCapabilities: 'CORE SYSTEM CAPABILITIES',
    everythingAccounting: 'Everything Your Enterprise Needs for Complete Financial Control',
    everythingAccountingSub: 'Streamline operations, automate tax reports, and eliminate manual errors with unified ERP software.',
    accountingPlans: 'Accounting & ERP Pricing Plans',
    accountingPlansSub: 'Flexible subscription tiers for startups, medium businesses, and large enterprise chains.',
    integrationWorkflow: 'Seamless 3-Step System Integration',
    integrationWorkflowSub: 'Our proven deployment roadmap ensuring 0% data loss and smooth staff adoption.',
    requestErpConsultation: 'Request Free ERP Consultation',
    exploreErpPlans: 'Explore ERP Plans',
    certifiedOdooPartner: 'Official Certified Odoo Implementation Partner',

    // Digital Marketing Localization
    marketingBadge: 'DIGITAL MARKETING & GROWTH',
    marketingHeroTitle: 'Data-Driven Digital Marketing & Growth Engineering',
    marketingHeroSub: 'We engineer high-ROI digital marketing campaigns, social media strategies, targeted paid advertising, and search engine dominance to scale your revenue.',
    coreMarketingPillars: 'CORE MARKETING PILLARS',
    endToEndGrowth: 'End-to-End Growth Engine for Your Brand',
    endToEndSub: 'Everything your brand needs to attract high-intent leads and maximize customer lifetime value.',
    marketingPackages: 'Growth Marketing Packages',
    marketingPackagesSub: 'Flexible monthly growth packages designed to deliver scalable ROI and brand visibility.',
    campaignShowcase: 'Omnichannel Campaign Excellence',
    campaignShowcaseSub: 'Explore our multi-channel marketing campaigns built across Facebook, Instagram, Google, and TikTok.',
    marketingWorkflow: 'Our Growth Strategy Workflow',
    marketingWorkflowSub: 'A structured data-first process to design, test, optimize, and scale your digital marketing.',
    startGrowthCampaign: 'Start Growth Campaign',
    explorePackages: 'Explore Packages',
    strategyWorkflowBadge: 'STRATEGY WORKFLOW',
    readyScaleBrand: 'Ready to Scale Your Brand Revenue?',
    readyScaleSub: 'Partner with our digital marketing specialists to launch high-converting multi-channel campaigns.',
    allChannels: 'All Channels',
    socialMediaAds: 'Social Media Ads',
    seoSearchDominance: 'SEO & Search',
    performanceMarketing: 'Performance Ads',

    // Web Design Page Localization
    webDesignBadge: 'WEB DESIGN & ENGINEERING',
    webDesignHeroTitle: 'Custom Web Design & Digital Engineering',
    webDesignHeroSub: 'We build high-performance, responsive websites and custom web applications designed to elevate your brand credibility, delight users, and drive maximum business conversions.',
    coreCapabilities: 'CORE CAPABILITIES',
    everythingNeeded: 'Everything Your Website Needs to Succeed',
    webDesignPillarsSub: 'From initial UI/UX wireframes to full-stack engineering, performance tuning, and technical SEO.',
    exploreShowcase: 'Explore Our Modern Website Showcase',
    showcaseSub: 'Discover some of our flagship website designs and interactive portal templates built for industry leaders.',
    processTitle: 'Our Web Design Process',
    processSub: 'A proven 4-stage engineering methodology to turn your concept into a live website.',
    startWebProject: 'Start Your Web Project',
    viewShowcase: 'View Project Showcase',
    portfolioShowcaseBadge: 'PORTFOLIO SHOWCASE',
    methodologyBadge: 'METHODOLOGY',
    readyLaunchWebsite: 'Ready to Launch Your Next-Gen Website?',
    readyLaunchSub: 'Let our engineering and marketing experts build your company\'s next website.',
    allProjects: 'All Projects',
    eCommerce: 'E-Commerce',
    corporate: 'Corporate',
    saasApps: 'SaaS & Apps',
    requestSimilarDesign: 'Request Similar Design',

    // Home Page Full Localization
    digitalPlatform: 'DIGITAL PLATFORM',
    heroHeading: 'Turning Ideas Into',
    heroDesc: 'We provide complete solutions in software, hardware, professional email, accounting systems, smart control, website development, and social media management — your business growth starts here.',
    webDesignAndServices: 'Web Design & Services',
    uptimeGuarantee: 'Uptime Guarantee',
    techSupport: 'Technical Support',
    globalClients: 'Global Clients',
    featuresBadge: 'FEATURES',
    allInOneTitle: 'Your All-in-One Tech Partner',
    allInOneDesc: 'From professional email and smart control to websites, accounting, and social media — our integrated services cover every step of your business growth.',
    integratedDigitalEngineering: 'Integrated Digital Engineering & Infrastructure',
    integratedDesc: 'We bring together software engineering, hardware installations, smart control systems, and enterprise accounting into a single unified partner for your organization.',
    lowCurrentCert: 'Certified Low-Current & Network Installations',
    cloudEmailCert: 'Automated Cloud Email & Domain Management',
    webErpCert: 'High-Performance Web & ERP Solutions',
    smartScalableTech: 'Smart & Scalable Tech',
    smartScalableTechDesc: 'Smart & scalable tech solutions',
    secureEmail: 'Secure Email',
    secureEmailDesc: 'Secure professional email',
    modernWebsites: 'Modern Websites',
    modernWebsitesDesc: 'Modern websites that convert',
    accountingSystems: 'Accounting Systems',
    accountingSystemsDesc: 'Accounting & business tracking',
    socialMedia: 'Social Media',
    socialMediaDesc: 'Social media that drives sales',
    proEmailCardDesc: 'Secure, branded email services that enhance your business credibility.',
    socialCardDesc: 'Engaging content and smart strategies to grow your audience and sales.',
    accCardDesc: 'Easy-to-use solutions to track finances, manage invoices, and control expenses.',
    networkCardDesc: 'Reliable, high-speed networking and server solutions built for your business.',
    pricingPlans: 'Pricing Plans',
    pricingSub: 'Choose the right professional email package for your business.',
    whatWeDo: 'WHAT WE DO',
    techSolutionsTitle: 'Tech Solutions Tailored to Your Business',
    techSolutionsSub: 'We specialize in delivering high-impact services in professional email, social media, accounting, networking, and servers — built to keep your business running smarter and faster.',
    worldwideTrust: 'WORLDWIDE TRUST',
    worldwideTrustTitle: 'Empowering Businesses with Professional Email Solutions',
    worldwideTrustSub: 'Trusted by companies worldwide for secure, branded, and reliable communication.',

    // Footer
    footerDesc: 'Empowering businesses with modern web engineering, ERP systems, smart control, and digital growth.',
    quickLinks: 'Quick Links',
    techSolutions: 'Tech Solutions',
    contactInfo: 'Contact Information'
  },
  ar: {
    // Navigation
    home: 'الرئيسية',
    webDesign: 'تصميم المواقع',
    digitalMarketing: 'التسويق الرقمي',
    accounting: 'الأنظمة المحاسبية',
    networkServers: 'الشبكات والسيرفرات',
    smartControl: 'التحكم الذكي',
    it: 'خدمات تكنولوجيا المعلومات',
    mailPro: 'بريد الشركات الاحترافي',
    cart: 'السلة',

    // Actions & Buttons
    getStarted: 'ابدأ الآن',
    contactUs: 'تواصل معنا',
    addToCart: 'أضف إلى السلة',
    subscribeNow: 'اشترك الآن',
    learnMore: 'اعرف المزيد',
    viewDetails: 'عرض التفاصيل',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    requestDemo: 'طلب تجربة مجانية',
    requestQuote: 'طلب عرض سعر',
    popularChoice: 'الأكثر طلباً',
    sale: 'خصم خاص',

    // Pricing Labels
    currency: 'ج.م',
    perMonth: '/شهرياً',

    // Terms & Conditions Localization
    legalBadge: 'الشروط القانونية والخصوصية',
    termsTitle: 'الشروط والأحكام وسياسة الخصوصية لشركة POM',
    lastUpdated: 'آخر تحديث: 2026',

    termsSec1Title: '1. سياسة الخصوصية لشركة POM',
    termsSec1P1: 'تحدد سياسة الخصوصية هذه (المشار إليها فيما يلي باسم "السياسة") الطريقة التي تجمع بها وكالة POM وتستخدم وتحافظ وتفصح عن المعلومات التي تم الحصول عليها عند وصولك إلى موقع POM وخدماتها الرقمية.',
    termsSec1P2: 'قد تخضع هذه السياسة للتعديل والتغيير من وقت لآخر، ويكون هذا التعديل سارياً فور نشره على موقع POM. يعتبر استمرارك في استخدام خدمات POM بمثابة موافقة كاملة على جميع الشروط.',

    termsSec2Title: '2. شروط البريد الإلكتروني والأنظمة المحاسبية والخدمات التقنية',
    termsSec2P1: 'تقدم وكالة POM خدمات استضافة البريد الإلكتروني الاحترافي، البنية التحتية للسيرفرات، تصميم المواقع، أنظمة التحكم الذكي، وتطبيقات الأنظمة المحاسبية (Odoo ERP). تجدد جميع اشتراكات الخدمات وفقاً لدورة الفوترة المحددة.',
    termsSec2Bullet1: 'يجب على المستخدمين الالتزام بسياسات استخدام البريد الإلكتروني القابلة ومكافحة الرسائل العشوائية (Anti-Spam).',
    termsSec2Bullet2: 'تُحدد مساحات تخزين صناديق البريد وفقاً للباقة المشترك فيها (الفردية: 5GB، الأعمال: 30GB، الاحترافية: 75GB).',
    termsSec2Bullet3: 'يتوفر الدعم الفني ومراقبة استقرار الشبكات على مدار 24/7 لعملاء الاستضافة والسيرفرات النشطين.',

    termsSec3Title: '3. الملكية الفكرية والعلامات التجارية',
    termsSec3P1: 'حقوق الطبع والنشر © 2021 – 2026 محفوظة لشركة POM Operating Company. تعتبر العلامة التجارية واللوجو الخاص بـ pomagency علامات تجارية مسجلة ومحمية بموجب القانون.',

    // Pricing Plans Translation
    planIndividual: 'باقة الفردي',
    planIndividualSub: 'استخدام فردي',
    planBusiness: 'باقة الأعمال',
    planBusinessSub: 'مستخدمين متعددين',
    planProfessional: 'الباقة الاحترافية',
    planProfessionalSub: 'مستخدمين متعددين',

    planStarterAccounting: 'المحاسبة المبتدئة',
    planStarterAccountingSub: 'للشركات الناشئة والمحلات',
    planBusinessERP: 'إدارة المؤسسات ERP',
    planBusinessERPSub: 'للشركات المتنامية والمتوسطة',
    planEnterpriseSuite: 'جناح الشركات الكبرى',
    planEnterpriseSuiteSub: 'للمؤسسات الكبرى متعددة الفروع',

    planStarterMarketing: 'التسويق المبتدئ',
    planStarterMarketingSub: 'للشركات الناشئة والعلامات الجديدة',
    planGrowthProMarketing: 'باقة نمو التسويق الاحترافي',
    planGrowthProMarketingSub: 'للمتاجر والشركات للتوسع السريع',
    planEnterpriseDominance: 'الهيمنة والتوسع الشامل',
    planEnterpriseDominanceSub: 'لكبرى العلامات والقنوات المتعددة',

    planStarterIT: 'الدعم الفني المبتدئ',
    planStarterITSub: 'للشركات الناشئة وفرق العمل عن بُعد',
    planManagedITPro: 'إدارة IT الاحترافية',
    planManagedITProSub: 'للشركات المتوسطة والمكاتب',
    planEnterpriseCareSLA: 'عقد اتفاقية المستوى SLA',
    planEnterpriseCareSLASub: 'للمؤسسات الكبرى متعددة الفروع',

    // Pricing Features Bullet Points
    feat1Mailbox: 'يتضمن صندوق بريد واحد',
    feat5GB: 'مساحة 5 جيجابايت للبريد',
    featCloudInfra: 'بنية تحتية سحابية فائقة الأمان',
    featAntivirus: 'فحص دوري وحماية من الفيروسات',
    feat3Mailboxes: 'يتضمن 3 صناديق بريد رسمية',
    feat30GB: 'مساحة 30 جيجابايت للبريد',
    featFullMobileSync: 'دعم المزامنة الكاملة مع الهواتف الذكية',
    feat5Mailboxes: 'يتضمن 5 صناديق بريد رسمية',
    feat75GB: 'مساحة 75 جيجابايت للبريد',
    featFreeDomain: 'نطاق (دومين) خاص مجاني',

    // IT Services Page Localization
    itBadge: 'خدمات IT المُدارة',
    itHeroTitle: 'خدمات إدارة تكنولوجيا المعلومات ودعم البنية التحتية للمؤسسات',
    itHeroSub: 'نوفر خدمة الدعم الفني لتقنية المعلومات على مدار 24/7، الحماية والأمن السيبراني، إدارة البنية السحابية، صيانة الأجهزة، واتفاقيات مستوى الخدمة SLA.',
    coreITServices: 'خدمات تقنية المعلومات الرئيسية',
    everythingIT: 'دعم متكامل لتكنولوجيا المعلومات والأمن السيبراني لمؤسستك',
    everythingITSub: 'تقليل فترات التوقف، حماية بيانات الشركة، وتسريع التحول الرقمي مع مهندسي IT معتمدين.',
    itPackages: 'باقات دعم وتطوير تكنولوجيا المعلومات',
    itPackagesSub: 'مستويات خدمة مرنة تضمن الدعم الفني الفوري، الصيانة الميدانية، ومراقبة استقرار الشبكات.',
    requestITAudit: 'طلب فحص IT مجاني',
    exploreITPackages: 'استعراض باقات IT',
    itServicesCtaTitle: 'هل تريد استشارة وفحص مجاني لبنية IT بشركتك؟',
    itServicesCtaSub: 'تواصل مع المهندسين المعتمدين لدينا للحصول على معاينة فورية ومخطط شامل.',
    managedItTag: 'خدمة IT مُدارة',

    // Mail Professional Page Localization
    mailBadge: 'المميزات الرئيسية',
    mailHeroTitle: 'إنشاء بريد إلكتروني احترافي لنشاطك التجاري',
    mailHeroSub: 'عنوان بريد إلكتروني يتطابق مع النطاق الخاص بك لجعل علامتك التجارية تبدو أكثر مصداقية وتعزيز ثقة العملاء.',
    customDomainAccounts: 'حسابات بريد الكتروني باسم نطاقك الخاص (Custom Domain)',
    cloudInfraSecurity: 'بنية تحتية سحابية مؤسسية وحماية معتمدة من الفيروسات',
    mobileDesktopSync: 'دعم المزامنة الكاملة على الموبايل وأجهزة الكمبيوتر',
    howItWorks: '4 خطوات لإعداد البريد الإلكتروني الاحترافي',
    howItWorksSub: 'احصل على بريد إلكتروني باسم نطاقك الخاص في دقائق معدودة.',

    step1Title: 'إنشاء بريد إلكتروني احترافي لنشاطك التجاري',
    step1Desc: 'عنوان بريد إلكتروني يتطابق مع النطاق الخاص بك لجعل علامتك التجارية تبدو أكثر مصداقية وتعزيز الثقة.',
    step2Title: 'اختيار خطة استضافة البريد الإلكتروني',
    step2Desc: 'هل تدير شركة جديدة أو متنامية؟ اختر من بين باقات الفردي، الأعمال، أو الباقة الاحترافية.',
    step3Title: 'الانتقال إلى عملية الدفع',
    step3Desc: 'حدد عدد صناديق البريد وفترة الاشتراك. بعد اكتمال عملية الدفع، سيتم توجيهك مباشرة إلى لوحة تحكم حساب الاستضافة الخاص بك.',
    step4Title: 'تهيئة استضافة البريد الإلكتروني',
    step4Desc: 'أخيراً، قم بإنشاء حساب بريد إلكتروني وضبط إعدادات الـ DNS ومزامنة البريد مع كافة أجهزتك. كل ما تبقى هو إرسال إيميلاتك.',

    needMore: 'تحتاج خطة مخصصة أكبر؟',
    needMoreDesc: 'إذا كنت بحاجة إلى أكثر من 50 حساب بريد إلكتروني أو تريد بريدًا خاصًا لأكثر من 20 نطاقًا، فتواصل معنا وسينشئ فريقنا خطة مخصصة لشركتك.',

    servicesBadge: 'الخدمات المتقدمة',
    aiDevTitle: 'تطوير الذكاء الاصطناعي: حلول متطورة لمجالك',
    aiDevSub: 'نبتكر حلول ذكاء اصطناعي وأتمتة متطورة لدعم نمو وأداء نشاطك التجاري والمؤسسي.',
    seoOptimization: 'تحسين محركات البحث (SEO)',
    seoOptDesc: 'تصدر النتائج الأولى على محركات البحث وجلب عملاء مهتمين ومستهدفين لخدماتك.',
    socialEngagement: 'التفاعل مع السوشيال ميديا',
    socialEngDesc: 'استراتيجيات تفاعل ومحتوى يومي مبتكر لبناء مجتمع قوي وزيادة المبيعات.',
    contentMarketing: 'التسويق بالمحتوى',
    contentMktDesc: 'صياغة نصوص إعلانية ومحتوى تسويقي مؤثر يضاعف نسب التحويل والمبيعات.',

    companyTimelineBadge: 'الجدول الزمني للشركة',
    companyTimelineTitle: 'مسيرة وتاريخ الشركة',
    companyTimelineSub: 'خطوات ومحطات نجاح وتوسع الشركة عبر السنوات لتقديم أفضل خدمة لعملائنا.',

    event1Title: 'التأسيس في الولايات المتحدة',
    event1Desc: 'بدء الانطلاقة الرسمية وتأسيس الخدمات التقنية والحلول السحابية الأولى.',
    event2Title: 'افتتاح المكاتب الجديدة',
    event2Desc: 'التوسع الدولي وافتتاح الفروع والمكاتب الجديدة لتغطية كافة متطلبات العملاء.',
    event3Title: 'رضا العملاء والورش',
    event3Desc: 'التفوق في تقديم خدمات دعم استثنائية وعقد ورش تطويرية عالية الكفاءة.',
    event4Title: 'التطور المستمر والتوسع',
    event4Desc: 'إعادة الابتكار وتطوير الخدمات ومواكبة أحدث تقنيات تكنولوجيا المعلومات.',

    getInTouch: 'تواصل معنا الآن',

    // Network & Servers Page Localization
    networkBadge: 'البنية التحتية للمؤسسات',
    networkHeroTitle: 'هندسة وتأسيس الشبكات والسيرفرات عالية الأداء',
    networkHeroSub: 'نقوم بتصميم وتثبيت وتأمين الشبكات فائقة السرعة، السيرفرات المخصصة، نطاقات Active Directory، وأنظمة النسخ الاحتياطي التلقائي.',
    coreNetworkServices: 'خدمات البنية التحتية الرئيسية',
    everythingNetwork: 'حلول شبكات وسيرفرات معتمدة تضمن أقصى استقرار',
    everythingNetworkSub: 'مصممة لضمان استقرار الشبكة بنسبة 99.99% بدون أي فقدان للبيانات وحماية كاملة بجدران نارية.',
    serverArchitectures: 'أنظمة وهياكل السيرفرات المؤسسية',
    serverArchitecturesSub: 'أجهزة سيرفرات فائقة القدرة مجهزة لتقنيات المحاكاة الافتراضية، التخزين، وإدارة النطاقات.',
    requestNetworkConsultation: 'طلب استشارة شبكات',
    exploreServerSolutions: 'استعراض حلول السيرفرات',
    customBlueprintBadge: 'مخطط مخصص',
    needCustomBlueprint: 'هل تحتاج مخطط شبكات وسيرفرات مخصص لشركتك؟',
    needCustomBlueprintSub: 'تواصل مع مهندسي الشبكات المعتمدين لدينا للحصول على معاينة ميدانية ومخطط هندسي متكامل.',

    // Accounting Page Localization
    accountingBadge: 'أنظمة ERP والحسابات',
    accountingHeroTitle: 'الأنظمة المحاسبية الذكية وحلول Odoo ERP للمؤسسات الحديثة',
    accountingHeroSub: 'سيطر بالكامل على الصحة المالية لشركتك والفاتورة الإلكترونية والمخازن والمرتبات مع حلول Odoo ERP المعتمدة.',
    accountingCapabilities: 'قدرات وإمكانيات النظام المحاسبي',
    everythingAccounting: 'كل ما تحتاجه مؤسستك لإدارة مالية متكاملة',
    everythingAccountingSub: 'تسهيل العمليات التشغيلية، إصدار الإقرارات الضريبية تلقائياً، وإلغاء الأخطاء اليدوية بنظام ERP موحد.',
    accountingPlans: 'خطط وأسعار الأنظمة المحاسبية والـ ERP',
    accountingPlansSub: 'باقات اشتراك مرنة تناسب الشركات الناشئة، المتوسطة، والسلاسل التجارية الكبرى.',
    integrationWorkflow: 'خطوات الربط والدمج الثلاثية',
    integrationWorkflowSub: 'خطة عمل مجربة وموثوقة لضمان نقل البيانات بدون أي فقدان 0% وتدريب فريق عملك.',
    requestErpConsultation: 'طلب استشارة ERP مجانية',
    exploreErpPlans: 'استعراض باقات ERP',
    certifiedOdooPartner: 'شريك معتمد رسمي لتطبيق وتنفيذ أنظمة Odoo',

    // Digital Marketing Localization
    marketingBadge: 'التسويق الرقمي والنمو',
    marketingHeroTitle: 'التسويق الرقمي القائم على البيانات واستراتيجيات النمو',
    marketingHeroSub: 'نقوم بصياغة حملات تسويق رقمي عالية العائد واستراتيجيات تواصل اجتماعي وإعلانات ممولة مستهدفة وتصدر محركات البحث لزيادة مبيعاتك.',
    coreMarketingPillars: 'ركائز ودعائم التسويق',
    endToEndGrowth: 'منظومة نمو متكاملة لعلامتك التجارية',
    endToEndSub: 'كل ما تحتاجه علامتك التجاريّة وجذب العملاء المهتمين وزيادة المبيعات.',
    marketingPackages: 'باقات التسويق الرقمي والنمو',
    marketingPackagesSub: 'باقات شهرية مرنة مصممة لتحقيق أعلى عائد على الاستثمار وزيادة انتشار العلامة التجارية.',
    campaignShowcase: 'معرض إعلانات وحملات التسويق',
    campaignShowcaseSub: 'استكشف حملاتنا التسويقية الناجحة عبر فيسبوك، إنستغرام، جوجل، وتيك توك.',
    marketingWorkflow: 'مسار استراتيجية النمو والتسويق',
    marketingWorkflowSub: 'منهجية منظمة قائمة على تحليلات البيانات للتصميم والاختبار والمكاسب التسويقية المستمرة.',
    startGrowthCampaign: 'ابدأ حملتك التسويقية الآن',
    explorePackages: 'استعراض الباقات',
    strategyWorkflowBadge: 'خطوات استراتيجية النمو',
    readyScaleBrand: 'هل أنت جاهز لتكبير وزيادة مبيعات علامتك التجارية؟',
    readyScaleSub: 'تواصل مع خبراء التسويق الرقمي لدينا لإطلاق حملات تسويقية متكاملة عالية العائد.',
    allChannels: 'جميع القنوات',
    socialMediaAds: 'إعلانات السوشيال ميديا',
    seoSearchDominance: 'تصدر محركات البحث',
    performanceMarketing: 'التسويق القائم على الأداء',

    // Web Design Page Localization
    webDesignBadge: 'تصميم وهندسة المواقع',
    webDesignHeroTitle: 'تصميم المواقع وتطوير الهندسة الرقمية',
    webDesignHeroSub: 'نقوم ببناء مواقع إلكترونية متجاوبة وعالية الأداء وتطبيقات ويب مخصصة لتعزيز مصداقية علامتك التجارية وزيادة المبيعات والتحويلات.',
    coreCapabilities: 'القدرات والخدمات المتاحة',
    everythingNeeded: 'كل ما يحتاجه موقعك الإلكتروني للنجاح',
    webDesignPillarsSub: 'من تصميم الواجهات سريعة التجاوب إلى البرمجة الكاملة وتصدر محركات البحث.',
    exploreShowcase: 'استكشف معرض نماذج المواقع الحديثة',
    showcaseSub: 'نماذج وتصميمات مواقع حديثة وتفاعلية مصممة خصيصاً لكبرى الشركات والمتاجر.',
    processTitle: 'مراحل وخطوات تصميم المواقع',
    processSub: 'منهجية هندسية من 4 مراحل لتحويل فكرة موقعك إلى واقع حي واحترافي.',
    startWebProject: 'ابدأ مشروع موقعك الآن',
    viewShowcase: 'استعراض النماذج',
    portfolioShowcaseBadge: 'معرض الأعمال',
    methodologyBadge: 'خطوات العمل',
    readyLaunchWebsite: 'هل أنت جاهز لإطلاق موقعك الإلكتروني الحديث؟',
    readyLaunchSub: 'دع خبراء البرمجة والتسويق لدينا يبنون الموقع القادم لشركتك بأحدث المعايير.',
    allProjects: 'جميع المشاريع',
    eCommerce: 'المتاجر الإلكترونية',
    corporate: 'مواقع الشركات',
    saasApps: 'المنصات والتطبيقات',
    requestSimilarDesign: 'طلب تصميم مماثل',

    // Home Page Full Localization
    digitalPlatform: 'منصة رقمية',
    heroHeading: 'تحويل الأفكار إلى',
    heroDesc: 'نحن نقدم حلولاً متكاملة في البرمجيات والأجهزة والبريد الإلكتروني الاحترافي والأنظمة المحاسبية والتحكم الذكي وتطوير المواقع والتسويق — نمو أعمالك يبدأ من هنا.',
    webDesignAndServices: 'تصميم المواقع والخدمات',
    uptimeGuarantee: 'ضمان تشغيل واستقرار 99.9%',
    techSupport: 'دعم فني متواصل 24/7',
    globalClients: 'عميل محلي وعالمي',
    featuresBadge: 'المميزات',
    allInOneTitle: 'شريكك التقني المتكامل',
    allInOneDesc: 'من البريد الاحترافي والتحكم الذكي إلى المواقع الإلكترونية والمحاسبة والتسويق — خدماتنا تغطي جميع مراحل نمو عملك.',
    integratedDigitalEngineering: 'الهندسة الرقمية والبنية التحتية المتكاملة',
    integratedDesc: 'نجمع بين هندسة البرمجيات، تركيبات الشبكات والأنظمة، شبكات التحكم الذكي، وأنظمة ERP المحاسبية تحت سقف شريك تقني واحد لمؤسستك.',
    lowCurrentCert: 'تركيبات وشبكات معتمدة وشاملة',
    cloudEmailCert: 'إدارة السيرفرات والنطاقات والبريد السحابي',
    webErpCert: 'حلول الويب المتقدمة وأنظمة الـ ERP',
    smartScalableTech: 'تكنولوجيا ذكية وقابلة للتوسع',
    smartScalableTechDesc: 'حلول تقنية ذكية وقابلة للنمو',
    secureEmail: 'بريد سحابي آمن',
    secureEmailDesc: 'بريد إلكتروني مخصص ومؤمن بالكامل',
    modernWebsites: 'مواقع حديثة عالية الأداء',
    modernWebsitesDesc: 'مواقع إلكترونية سريعة وجذابة',
    accountingSystems: 'أنظمة محاسبية متطورة',
    accountingSystemsDesc: 'متابعة وإدارة الحسابات بدقة',
    socialMedia: 'تسويق رقمي وإعلانات',
    socialMediaDesc: 'تسويق رقمي يزيد مبيعاتك',
    proEmailCardDesc: 'خدمات بريد إلكتروني رسمية ومؤمنة تعزز مصداقية واسم عملك التجاري.',
    socialCardDesc: 'محتوى جذاب وإستراتيجيات تسويقية لزيادة متابعيك ومبيعاتك.',
    accCardDesc: 'حلول سهلة لإدارة الحسابات، إصدار الفواتير الإلكترونية، والتحكم بالمرتبات.',
    networkCardDesc: 'شبكات وسيرفرات فائقة السرعة معتمدة لحماية واستقرار شركتك.',
    pricingPlans: 'خطط الأسعار',
    pricingSub: 'اختر باقة البريد الإلكتروني أو الحل المناسب لشركتك.',
    whatWeDo: 'ماذا نقدم',
    techSolutionsTitle: 'حلول تقنية مخصصة لنشاطك التجاري',
    techSolutionsSub: 'نحن متخصصون في تقديم خدمات عالية التأثير في البريد الإلكتروني، شبكات التواصل، المحاسبة، الشبكات والسيرفرات.',
    worldwideTrust: 'ثقة عالمية ومحلية',
    worldwideTrustTitle: 'تمكين الشركات بحلول البريد الإلكتروني والأنظمة التقنية',
    worldwideTrustSub: 'محل ثقة كبرى الشركات والتجار لتوفير اتصالات وأنظمة آمنة وموثوقة.',

    // Footer
    footerDesc: 'تمكين الشركات والمؤسسات بأحدث تكنولوجيات البرمجة، أنظمة ERP المحاسبية، التحكم الذكي، والتسويق الرقمي.',
    quickLinks: 'روابط سريعة',
    techSolutions: 'الحلول التقنية',
    contactInfo: 'معلومات الاتصال'
  },
  tr: {
    // Navigation
    home: 'Ana Sayfa',
    webDesign: 'Web Tasarım',
    digitalMarketing: 'Dijital Pazarlama',
    accounting: 'Muhasebe Sistemleri (Odoo)',
    networkServers: 'Ağ ve Sunucular',
    smartControl: 'Akıllı Kontrol ve Zayıf Akım',
    it: 'BT Hizmetleri',
    mailPro: 'Kurumsal E-Posta',
    cart: 'Sepet',

    // Actions & Buttons
    getStarted: 'Hemen Başlayın',
    contactUs: 'Bize Ulaşın',
    addToCart: 'Sepete Ekle',
    subscribeNow: 'Şimdi Abone Ol',
    learnMore: 'Daha Fazla Bilgi',
    viewDetails: 'Detayları İncele',
    allRightsReserved: 'Tüm hakları saklıdır.',
    requestDemo: 'Ücretsiz Demo Talebi',
    requestQuote: 'Teklif Alın',
    popularChoice: 'EN ÇOK TERCİH EDİLEN',
    sale: 'ÖZEL FIRSAT',

    // Pricing Labels
    currency: 'EGP',
    perMonth: '/Ay',

    // Terms & Conditions Localization
    legalBadge: 'YASAL VE GİZLİLİK',
    termsTitle: 'Şartlar ve Koşullar & POM Gizlilik Politikası',
    lastUpdated: 'Son Güncelleme: 2026',

    termsSec1Title: '1. POM Gizlilik Politikası',
    termsSec1P1: 'Bu Gizlilik Politikası ("Politika"), POM Agency\'nin POM web sitesine ve dijital hizmetlerine eriştiğinizde elde edilen bilgileri nasıl topladığını, kullandığını, koruduğunu ve açıkladığını belirler.',
    termsSec1P2: 'Bu politika zaman zaman güncellenebilir ve değişiklikler web sitesinde yayınlandığı andan itibaren geçerli olur. Hizmetlerimizi kullanmaya devam etmeniz tüm şartları kabul ettiğiniz anlamına gelir.',

    termsSec2Title: '2. Profesyonel E-Posta & BT Hizmet Şartları',
    termsSec2P1: 'POM Agency; profesyonel e-posta barındırma, sunucu altyapısı, web tasarımı, akıllı kontrol sistemleri ve muhasebe yazılımı (Odoo ERP) uygulamaları sunar. Tüm hizmet abonelikleri seçilen faturalandırma döngüsüne göre yenilenir.',
    termsSec2Bullet1: 'Kullanıcılar kabul edilebilir e-posta kullanım politikalarına ve anti-spam standartlarına uymalıdır.',
    termsSec2Bullet2: 'Posta kutusu depolama kotaları abone olunan pakete göre belirlenir (Bireysel: 5GB, İş: 30GB, Profesyonel: 75GB).',
    termsSec2Bullet3: 'Aktif hosting ve sunucu müşterilerimiz için 7/24 teknik destek ve ağ izleme hizmeti sağlanmaktadır.',

    termsSec3Title: '3. Fikri Mülkiyet ve Ticari Markalar',
    termsSec3P1: 'Telif Hakkı © 2021 – 2026 POM Agency Operating Company, Tüm Hakları Saklıdır. pomagency kelime markası ve logosu tescilli ticari markalardır.',

    // Pricing Plans Translation
    planIndividual: 'Bireysel E-Posta',
    planIndividualSub: 'Tek Kullanıcı',
    planBusiness: 'Kurumsal E-Posta',
    planBusinessSub: 'Çoklu Kullanıcı',
    planProfessional: 'Profesyonel E-Posta',
    planProfessionalSub: 'Büyük Ekipler',

    planStarterAccounting: 'Başlangıç Muhasebe',
    planStarterAccountingSub: 'Küçük İşletmeler ve Girişimler',
    planBusinessERP: 'Kurumsal ERP',
    planBusinessERPSub: 'Büyüyen Şirketler',
    planEnterpriseSuite: 'Enterprise ERP Paketi',
    planEnterpriseSuiteSub: 'Büyük Ölçekli Kuruluşlar',

    planStarterMarketing: 'Başlangıç Pazarlama',
    planStarterMarketingSub: 'Yeni Markalar ve Girişimler',
    planGrowthProMarketing: 'Büyüme Odaklı Pro Pazarlama',
    planGrowthProMarketingSub: 'E-Ticaret ve Büyüyen Şirketler',
    planEnterpriseDominance: 'Tam Pazar Hakimiyeti',
    planEnterpriseDominanceSub: 'Lider Markalar ve Holdingler',

    planStarterIT: 'Temel BT Desteği',
    planStarterITSub: 'Küçük İşletmeler ve Uzaktan Ekipler',
    planManagedITPro: 'Yönetilen BT Pro',
    planManagedITProSub: 'Orta Ölçekli Şirketler',
    planEnterpriseCareSLA: 'Kurumsal SLA Bakım Sözleşmesi',
    planEnterpriseCareSLASub: 'Büyük Kurumlar ve Çok Şubeli Yapılar',

    // Pricing Features Bullet Points
    feat1Mailbox: '1 adet kurumsal e-posta hesabı',
    feat5GB: '5 GB yüksek hızlı e-posta alanı',
    featCloudInfra: 'Güvenli bulut altyapısı',
    featAntivirus: 'Otomatik antivirüs ve spam koruması',
    feat3Mailboxes: '3 adet kurumsal e-posta hesabı',
    feat30GB: '30 GB paylaşımlı bulut depolama',
    featFullMobileSync: 'Tam mobil ve Outlook senkronizasyonu',
    feat5Mailboxes: '5 adet kurumsal e-posta hesabı',
    feat75GB: '75 GB geniş bulut depolama',
    featFreeDomain: 'Ücretsiz alan adı (Domain) dahil',

    // IT Services Page Localization
    itBadge: 'YÖNETİLEN BT HİZMETLERİ',
    itHeroTitle: 'Kurumsal Yönetilen BT Hizmetleri ve Altyapı Desteği',
    itHeroSub: '7/24 yönetilen teknik destek, siber güvenlik koruması, hibrit bulut yönetimi, donanım bakımı ve SLA garantili BT operasyonları sunuyoruz.',
    coreITServices: 'TEMEL YÖNETİLEN BT HİZMETLERİ',
    everythingIT: 'Kurumunuz İçin Uçtan Uca Yönetilen BT ve Siber Güvenlik',
    everythingITSub: 'Kesintileri en aza indirin, kurumsal verilerinizi koruyun ve sertifikalı BT mühendislerimizle dijital dönüşümünüzü hızlandırın.',
    itPackages: 'Yönetilen BT Destek Paketleri',
    itPackagesSub: 'Uzaktan yardım masası, yerinde donanım bakımı ve proaktif ağ izleme sunan esnek SLA paketleri.',
    requestITAudit: 'Ücretsiz BT Denetimi İsteyin',
    exploreITPackages: 'BT Paketlerini İnceleyin',
    itServicesCtaTitle: 'Şirketinizin BT Güvenliğini ve İstikrarını Yükseltmeye Hazır mısınız?',
    itServicesCtaSub: 'Sertifikalı ekibimizle yerinde BT denetimi ve altyapı yol haritası planlayın.',
    managedItTag: 'Yönetilen BT Hizmeti',

    // Mail Professional Page Localization
    mailBadge: 'TEMEL ÖZELLİKLER',
    mailHeroTitle: 'İşletmeniz İçin Profesyonel Kurumsal E-Posta Oluşturun',
    mailHeroSub: 'Markanıza güvenilirlik kazandıran özel alan adınızla eşleşen e-posta adresleri (adınız@sirketiniz.com). Gelişmiş güvenlik ve kesintisiz senkronizasyon.',
    customDomainAccounts: 'Özel alan adı (Domain) e-posta hesapları',
    cloudInfraSecurity: 'Kurumsal bulut altyapısı ve antivirüs güvenliği',
    mobileDesktopSync: 'Akıllı telefon ve masaüstü tam senkronizasyon',
    howItWorks: 'Profesyonel E-Postanızı Kurmak İçin 4 Adım',
    howItWorksSub: 'Dakikalar içinde kurumsal e-postanızı aktif hale getirin.',

    step1Title: 'İşletmeniz için profesyonel e-posta oluşturun',
    step1Desc: 'Marka itibarınızı güçlendirmek için alan adınıza özel kurumsal e-posta adresi.',
    step2Title: 'E-posta hosting paketinizi seçin',
    step2Desc: 'İhtiyacınıza uygun Bireysel, Kurumsal veya Profesyonel paketlerden birini seçin.',
    step3Title: 'Ödeme aşamasına geçin',
    step3Desc: 'Posta kutusu sayısını ve abonelik süresini belirleyin, ardından kontrol panelinize yönlendirilin.',
    step4Title: 'E-posta kurulumunuzu tamamlayın',
    step4Desc: 'DNS kayıtlarını yapılandırın, e-postanızı telefon ve bilgisayarınızla senkronize edin.',

    needMore: 'Daha büyük özel bir plana mı ihtiyacınız var?',
    needMoreDesc: '50\'den fazla hesaba veya 20\'den fazla alan adına ihtiyacınız varsa, ekibimiz firmanıza özel teklif hazırlasın.',

    servicesBadge: 'HİZMETLER',
    aiDevTitle: 'Yapay Zeka ve Yazılım Geliştirme: Sektörünüze Özel Çözümler',
    aiDevSub: 'İşletmenizi geleceğe taşıyan modern yapay zeka entegrasyonları ve özel yazılım mimarileri.',
    seoOptimization: 'SEO Optimizasyonu',
    seoOptDesc: 'Google aramalarında en üst sıralara çıkmanızı sağlayan teknik ve içerik SEO stratejileri.',
    socialEngagement: 'Sosyal Medya Yönetimi',
    socialEngDesc: 'Hedef kitlenizle etkileşimi artıran ve doğrudan satış getiren stratejik içerik yönetimi.',
    contentMarketing: 'İçerik Pazarlaması',
    contentMktDesc: 'Marka bilinirliğinizi artıran yüksek kaliteli görsel ve video prodüksiyonları.',

    companyTimelineBadge: 'ŞİRKET ZAMAN ÇİZELGESİ',
    companyTimelineTitle: 'Gelişim Yolculuğumuz',
    companyTimelineSub: 'Kurulduğumuz günden bugüne başarıyla tamamlanan kurumsal projelerimiz.',

    event1Title: 'Kuruluş & İlk Adımlar',
    event1Desc: 'Dijital mühendislik ve kurumsal altyapı hizmetlerinin başlangıcı.',
    event2Title: 'Bölgesel Büyüme & Yeni Ofisler',
    event2Desc: 'Mısır ve Körfez bölgesinde genişleyen müşteri ağı ve altyapı yatırımları.',
    event3Title: '%100 Müşteri Memnuniyeti',
    event3Desc: '500+ kurumsal müşteriye kesintisiz hizmet ve destek.',
    event4Title: 'Yeni Nesil Teknolojiler',
    event4Desc: 'Yapay zeka, Odoo ERP ve akıllı bina otomasyonu ile entegre ekosistem.',

    getInTouch: 'İletişime Geçin',

    // Network & Servers Page Localization
    networkBadge: 'KURUMSAL ALTYAPI',
    networkHeroTitle: 'Yüksek Performanslı Ağ ve Sunucu Mühendisliği',
    networkHeroSub: 'Yüksek hızlı kurumsal ağlar, özel fiziksel sunucular, Active Directory alanları ve yedekleme altyapıları tasarlıyor ve kuruyoruz.',
    coreNetworkServices: 'TEMEL ALTYAPI HİZMETLERİ',
    everythingNetwork: 'Maksimum Çalışma Süresi İçin Sertifikalı Ağ ve Sunucu Çözümleri',
    everythingNetworkSub: '%99.99 ağ kararlılığı, sıfır veri kaybı ve güçlü güvenlik duvarı (Firewall) koruması.',
    serverArchitectures: 'Özel Kurumsal Sunucu Mimarileri',
    serverArchitecturesSub: 'Sanallaştırma, depolama ve etki alanı denetimi için tasarlanmış yüksek kapasiteli sunucu donanımları.',
    requestNetworkConsultation: 'Ağ Danışmanlığı İsteyin',
    exploreServerSolutions: 'Sunucu Çözümlerini Keşfedin',
    customBlueprintBadge: 'ÖZEL MİMARİ PLAN',
    needCustomBlueprint: 'Özel Kurumsal Ağ Planına mı İhtiyacınız Var?',
    needCustomBlueprintSub: 'Yerinde ağ denetimi ve mimari proje teklifi için sertifikalı ağ mühendislerimizle görüşün.',

    // Accounting Page Localization
    accountingBadge: 'ERP VE FİNANSAL SİSTEMLER',
    accountingHeroTitle: 'Modern İşletmeler İçin Akıllı Muhasebe ve Odoo ERP Sistemleri',
    accountingHeroSub: 'Sertifikalı Odoo ERP uygulamalarımızla finansal durumunuzu, e-fatura entegrasyonunu, stokları ve bordroyu tek noktadan yönetin.',
    accountingCapabilities: 'TEMEL SİSTEM YETENEKLERİ',
    everythingAccounting: 'Tam Finansal Kontrol İçin İşletmenizin İhtiyacı Olan Her Şey',
    everythingAccountingSub: 'Operasyonları kolaylaştırın, vergi raporlarını otomatikleştirin ve manuel hataları ortadan kaldırın.',
    accountingPlans: 'Muhasebe ve ERP Fiyatlandırma Paketleri',
    accountingPlansSub: 'Girişimler, KOBİ\'ler ve büyük holdingler için esnek abonelik katmanları.',
    integrationWorkflow: 'Kusursuz 3 Adımlı Entegrasyon',
    integrationWorkflowSub: '%0 veri kaybı ve hızlı personel adaptasyonu sağlayan kanıtlanmış kurulum yol haritamız.',
    requestErpConsultation: 'Ücretsiz ERP Danışmanlığı Alın',
    exploreErpPlans: 'ERP Paketlerini İnceleyin',
    certifiedOdooPartner: 'Resmi Sertifikalı Odoo Uygulama Partneri',

    // Digital Marketing Localization
    marketingBadge: 'DİJİTAL PAZARLAMA VE BÜYÜME',
    marketingHeroTitle: 'Veri Odaklı Dijital Pazarlama ve Büyüme Mühendisliği',
    marketingHeroSub: 'Gelirinizi artırmak için yüksek yatırım getirili dijital pazarlama kampanyaları, sosyal medya stratejileri ve arama motoru hakimiyeti inşa ediyoruz.',
    coreMarketingPillars: 'TEMEL PAZARLAMA DİREKLERİ',
    endToEndGrowth: 'Markanız İçin Uçtan Uca Büyüme Motoru',
    endToEndSub: 'Yüksek kaliteli potansiyel müşteriler çekmek ve satışları katlamak için gereken her şey.',
    marketingPackages: 'Büyüme Pazarlama Paketleri',
    marketingPackagesSub: 'Ölçeklenebilir ROI ve marka görünürlüğü sağlamak için tasarlanmış esnek aylık paketler.',
    campaignShowcase: 'Çok Kanallı Kampanya Başarıları',
    campaignShowcaseSub: 'Meta, Google, TikTok ve Snapchat üzerinde yürüttüğümüz başarılı pazarlama kampanyalarını keşfedin.',
    marketingWorkflow: 'Büyüme Stratejisi İş Akışımız',
    marketingWorkflowSub: 'Dijital pazarlamanızı tasarlamak, test etmek, optimize etmek ve ölçeklendirmek için veri odaklı süreç.',
    startGrowthCampaign: 'Büyüme Kampanyası Başlatın',
    explorePackages: 'Paketleri İnceleyin',
    strategyWorkflowBadge: 'STRATEJİK İŞ AKIŞI',
    readyScaleBrand: 'Marka Gelirinizi Ölçeklendirmeye Hazır mısınız?',
    readyScaleSub: 'Yüksek dönüşümlü çok kanallı kampanyalar başlatmak için dijital pazarlama uzmanlarımızla çalışın.',
    allChannels: 'Tüm Kanallar',
    socialMediaAds: 'Sosyal Medya Reklamları',
    seoSearchDominance: 'SEO ve Arama',
    performanceMarketing: 'Performans Reklamları',

    // Web Design Page Localization
    webDesignBadge: 'WEB TASARIM VE MÜHENDİSLİK',
    webDesignHeroTitle: 'Özel Web Tasarımı ve Dijital Mühendislik',
    webDesignHeroSub: 'Marka itibarınızı güçlendiren, kullanıcıları etkileyen ve dönüşümleri artıran yüksek performanslı, mobil uyumlu web siteleri geliştiriyoruz.',
    coreCapabilities: 'TEMEL YETENEKLER',
    everythingNeeded: 'Web Sitenizin Başarısı İçin Gereken Her Şey',
    webDesignPillarsSub: 'UI/UX tasarımından modern full-stack yazılıma, performans optimizasyonuna ve teknik SEO\'ya kadar.',
    exploreShowcase: 'Modern Web Sitesi Vitrinimizi İnceleyin',
    showcaseSub: 'Sektör liderleri için geliştirdiğimiz özel web tasarımlarını ve etkileşimli portal şablonlarını keşfedin.',
    processTitle: 'Web Geliştirme Sürecimiz',
    processSub: 'Fikrinizi çalışan canlı bir web sitesine dönüştüren 4 aşamalı mühendislik metodolojisi.',
    startWebProject: 'Web Projenizi Başlatın',
    viewShowcase: 'Projeleri İnceleyin',
    portfolioShowcaseBadge: 'PORTFÖY VİTRİNİ',
    methodologyBadge: 'METODOLOJİ',
    readyLaunchWebsite: 'Yeni Nesil Web Sitenizi Yayına Almaya Hazır mısınız?',
    readyLaunchSub: 'Uzman mühendislerimiz ve tasarımcılarımız şirketinizin yeni web sitesini inşa etsin.',
    allProjects: 'Tüm Projeler',
    eCommerce: 'E-Ticaret',
    corporate: 'Kurumsal',
    saasApps: 'SaaS & Uygulamalar',
    requestSimilarDesign: 'Benzer Tasarım İsteyin',

    // Home Page Full Localization
    digitalPlatform: 'DİJİTAL PLATFORM',
    heroHeading: 'Fikirleri Gerçeğe',
    heroDesc: 'Yazılım, donanım, kurumsal e-posta, muhasebe sistemleri, akıllı kontrol, web geliştirme ve dijital pazarlamada eksiksiz çözümler sunuyoruz — büyümeniz burada başlıyor.',
    webDesignAndServices: 'Web Tasarım ve Hizmetler',
    uptimeGuarantee: '%99.99 Çalışma Süresi Garantisi',
    techSupport: '7/24 Kesintisiz Teknik Destek',
    globalClients: 'Global ve Yerel Müşteri',
    featuresBadge: 'ÖZELLİKLER',
    allInOneTitle: 'Hepsi Bir Arada Teknoloji Ortağınız',
    allInOneDesc: 'Kurumsal e-postadan akıllı kontrole, web sitelerinden ERP muhasebe ve pazarlamaya kadar — entegre hizmetlerimiz işinizi büyütür.',
    integratedDigitalEngineering: 'Entegre Dijital Mühendislik ve Altyapı',
    integratedDesc: 'Yazılım mühendisliği, donanım kurulumları, akıllı kontrol ağları ve ERP muhasebe sistemlerini kurumunuz için tek bir güvenilir çatı altında birleştiriyoruz.',
    lowCurrentCert: 'Sertifikalı Zayıf Akım ve Ağ Kurulumları',
    cloudEmailCert: 'Otomatik Bulut E-Posta ve Alan Adı Yönetimi',
    webErpCert: 'Yüksek Performanslı Web ve ERP Çözümleri',
    smartScalableTech: 'Akıllı ve Ölçeklenebilir Teknoloji',
    smartScalableTechDesc: 'Akıllı ve ölçeklenebilir teknoloji çözümleri',
    secureEmail: 'Güvenli E-Posta',
    secureEmailDesc: 'Güvenli kurumsal e-posta altyapısı',
    modernWebsites: 'Modern Web Siteleri',
    modernWebsitesDesc: 'Dönüşüm odaklı modern web siteleri',
    accountingSystems: 'Muhasebe Sistemleri',
    accountingSystemsDesc: 'Detaylı muhasebe ve finans takibi',
    socialMedia: 'Sosyal Medya & Pazarlama',
    socialMediaDesc: 'Satışları artıran dijital pazarlama',
    proEmailCardDesc: 'İşletmenizin güvenilirliğini artıran güvenli, özel alan adlı e-posta hizmetleri.',
    socialCardDesc: 'Kitlenizi ve satışlarınızı büyütmek için ilgi çekici içerikler ve akıllı stratejiler.',
    accCardDesc: 'Finansmanı takip etmek, faturaları yönetmek ve giderleri kontrol etmek için kolay çözümler.',
    networkCardDesc: 'İşletmeniz için tasarlanmış güvenilir, yüksek hızlı ağ ve sunucu çözümleri.',
    pricingPlans: 'Fiyatlandırma Paketleri',
    pricingSub: 'İşletmeniz için doğru kurumsal e-posta ve teknoloji paketini seçin.',
    whatWeDo: 'NELER YAPIYORUZ',
    techSolutionsTitle: 'İşletmenize Özel Teknoloji Çözümleri',
    techSolutionsSub: 'Kurumsal e-posta, sosyal medya, muhasebe, ağlar ve sunucularda yüksek etkili hizmetler sunma konusunda uzmanız.',
    worldwideTrust: 'KÜRESEL GÜVEN',
    worldwideTrustTitle: 'İşletmeleri Profesyonel Çözümlerle Güçlendiriyoruz',
    worldwideTrustSub: 'Güvenli, markalı ve güvenilir iletişim için dünya çapında şirketlerin tercihi.',

    // Footer
    footerDesc: 'Modern web mühendisliği, ERP sistemleri, akıllı kontrol ve dijital büyüme ile işletmeleri güçlendiriyoruz.',
    quickLinks: 'Hızlı Bağlantılar',
    techSolutions: 'Teknoloji Çözümleri',
    contactInfo: 'İletişim Bilgileri'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('pom_app_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('pom_app_lang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
